---
title: "HCV DAA"
output: html_document
date: "2025-11-20"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readxl)
library(openxlsx)

library(cowplot)
library(patchwork)
library(ggtext)
library(scales)
```

```{r}
# make df folder

dir.create("../figure", showWarnings = TRUE, recursive = FALSE, mode = "0777")
```

```{r}
# make df folder

dir.create("../df/daa/analysis", showWarnings = TRUE, recursive = FALSE, mode = "0777")
```

```{r}
df_daa_dem <- readRDS("../df/daa/format/df_daa_dem")
```

```{r}
df_cost_all <- readRDS("../rds/cost/df_cost_all")
```

```{r}
df_boj <- readRDS("../rds/boj/df_boj")
```


# df_daa_dem

```{r}
df_daa_dem %>% count(YEAR_str)
```


```{r}
df_daa_dem %>% count(DAA)
```


```{r}
df_daa_dem %>% count(SHEET)
```

```{r}
df_daa_dem_total <- df_daa_dem %>%
  distinct(FILE, SHEET, DAA, .keep_all = TRUE)
```

```{r}
df_exp_total <- expand_grid(YEAR_str = df_daa_dem_total$YEAR_str %>% unique(),
                      DAA = df_daa_dem_total$DAA %>% unique(),
                      SHEET = df_daa_dem_total$SHEET %>% unique()) %>%
  mutate(ID = paste0(YEAR_str, "_", SHEET, "_", DAA))
```

```{r}
df_anti_total <- df_exp_total %>%
  anti_join(df_daa_dem_total %>%
              mutate(ID = paste0(YEAR_str, "_", SHEET, "_", DAA)),
            by = join_by(ID))

df_anti_total
```


```{r}
# clean need to remove year prior to approval

df_anti_total %>%
  filter( (DAA == "SOF" & as.numeric(YEAR_str) >= 2015 & as.numeric(YEAR_str) <= 2023) |
           (DAA == "SOF/LDV" & as.numeric(YEAR_str) >= 2015) | 
            
            (DAA == "OBV/PTV/r" & as.numeric(YEAR_str) >= 2015 & as.numeric(YEAR_str) <= 2019)  |
           (DAA %in% c("EBR", "GZR") & as.numeric(YEAR_str) >= 2016  & as.numeric(YEAR_str) <= 2022) |
           (DAA %in% c("GLE/PIB") & as.numeric(YEAR_str) >= 2017) |
           (DAA %in% c("SOF/VEL") & as.numeric(YEAR_str) >= 2019)) 
  
```


```{r}
df_anti_total %>%
  filter(DAA =="SOF/VEL" & as.numeric(YEAR_str) >= 2019)
```


```{r}
# check discordance in combination therapy

df_daa_dem_total %>% 
  distinct(DAA, YEAR_str, SHEET, .keep_all = TRUE) %>%
  filter(DAA %in% c("DCV", "ASV", "EBR", "GZR")) %>%
  count(DAA, YEAR_str)

# DCV/ASV complete pairs
# EBR/GZR needs impution
```

```{r}
# check SHEET category in EBR/GZR

df_daa_dem_total %>% 
  distinct(DAA, YEAR_str, SHEET, .keep_all = TRUE) %>%
  filter(DAA %in% c("EBR", "GZR")) %>%
  count(DAA, YEAR_str)

#1 EBR 2018 1 category missing -> impute from GZR 2018

#2 GZR 2019 1 cateogry missing & EBR 2019 all missing -> impute 2 caterories in EBR from GZR
# unable to fill missing GZR
```


```{r}
df_daa_dem_total %>% 
  distinct(DAA, YEAR_str, SHEET, .keep_all = TRUE) %>%
   filter(DAA %in% c("DCV", "ASV")) %>%
  select(SHEET, DAA, TOTAL, YEAR_str) %>%
  pivot_wider(names_from = DAA, values_from = TOTAL, values_fill = 0)

# complete pairs for DCV/ASV
```



```{r}
df_daa_dem_total %>% 
  distinct(DAA, YEAR_str, SHEET, .keep_all = TRUE) %>%
   filter(DAA %in% c("DCV", "ASV")) %>%
  select(SHEET, DAA, TOTAL, YEAR_str) %>%
  pivot_wider(names_from = DAA, values_from = TOTAL, values_fill = 0) %>%
  mutate(RATIO = ASV/DCV) %>%
  ggplot(aes(SHEET, RATIO))+
  geom_boxplot()+
  geom_point()+
  scale_y_continuous(limits = c(0, 3),
                     breaks = seq(0, 3, 1))+
  theme_classic()
```

```{r}
df_daa_dem_total %>% 
   filter(DAA %in% c("DCV", "ASV")) %>%
  select(SHEET, DAA, TOTAL, YEAR_str) %>%
  pivot_wider(names_from = DAA, values_from = TOTAL, values_fill = 0) %>%
  mutate(RATIO = ASV/DCV) %>%
  group_by(SHEET) %>%
  summarise(MED = median(RATIO),
            MIN = min(RATIO),
            MAX = max(RATIO))
```

```{r}
df_daa_dem_total %>%
   filter(DAA %in% c("EBR", "GZR")) %>%
  select(SHEET, DAA, TOTAL, YEAR_str) %>%
  pivot_wider(names_from = DAA, values_from = TOTAL, values_fill = 0) %>%
  arrange(SHEET, YEAR_str)
```


```{r}
df_daa_dem_total %>%
   filter(DAA %in% c("EBR", "GZR")) %>%
  select(SHEET, DAA, TOTAL, YEAR_str) %>%
  pivot_wider(names_from = DAA, values_from = TOTAL, values_fill = 0) %>%
  filter(EBR != 0) %>%
  mutate(RATIO = GZR/EBR) %>%
  ggplot(aes(SHEET, RATIO))+
  geom_boxplot()+
  geom_point()+
  scale_y_continuous(limits = c(0, 3),
                     breaks = seq(0, 3, 1))+
  theme_classic()
```


```{r}
df_daa_dem_total %>%
   filter(DAA %in% c("EBR", "GZR")) %>%
  select(SHEET, DAA, TOTAL, YEAR_str) %>%
  pivot_wider(names_from = DAA, values_from = TOTAL, values_fill = 0) %>%
  filter(EBR != 0) %>%
  mutate(RATIO = GZR/EBR) %>%
  group_by(SHEET) %>%
    summarise(MED = median(RATIO),
            MIN = min(RATIO),
            MAX = max(RATIO))
```


```{r}
# fill zero
df_ebr_gzr_fill <- df_daa_dem_total %>%
   filter(DAA %in% c("EBR", "GZR")) %>%
  select(SHEET, DAA, TOTAL, YEAR_str) %>%
  pivot_wider(names_from = DAA, values_from = TOTAL, values_fill = 0) %>%
  filter(EBR == 0) %>%
  mutate(EBR = case_when(EBR == 0 ~ GZR/2,
                         .default = EBR))

df_ebr_gzr_fill
```

```{r}
df_ebr_gzr_long <- df_ebr_gzr_fill %>%
  pivot_longer(cols = c(GZR, EBR),
               names_to = "DAA",
               values_to = "TOTAL")

df_ebr_gzr_long
```


```{r}
# inspect discrepancies in combination therapy

df_daa_dem_total %>%
  filter(DAA %in% c("DCV", "ASV", "EBR", "GZR")) %>%
  ungroup() %>%
  group_by(DAA, YEAR_str) %>%
  summarise(SUM = sum(TOTAL)) %>% 
  ungroup() %>%
  pivot_wider(names_from = DAA, values_from = SUM) %>% View()

#内服　院外　missing in EBR
```

```{r}
# SHEET , YEAR_str, and DAA should give unique ID

df_daa_dem_total %>% nrow()

df_daa_dem_total %>%
  mutate(ID = str_c(SHEET, YEAR_str, DAA, sep = "_")) %>%
  distinct(ID) %>% nrow()
```

```{r}
# create ID for df_total to get COST_per

df_daa_dem_total <- df_daa_dem_total %>%
  mutate(ID = str_c(YEAR_str, DAA, sep = "_")) 
```


```{r}
# create ID for df liong

df_ebr_imp <- df_ebr_gzr_long %>%
  filter(DAA == "EBR") %>%
  mutate(ID = str_c(YEAR_str, DAA, sep = "_")) 

df_ebr_imp
```

```{r}
df_ebr_imp <- df_ebr_imp %>%
  left_join(df_daa_dem_total %>%
              distinct(COST_per, ID), 
            by = join_by(ID))

df_ebr_imp
```




```{r}
df_daa_dem_total %>% filter()
```


```{r}
# check GZR for 2018/2019 in total

df_daa_dem_total %>%
  filter(YEAR_str %in% c("2018", "2019")) %>%
  count(DAA, YEAR_str, COST_per)
```


```{r}
# GZR the same price

df_ebr_imp <- df_ebr_imp %>%
  mutate(COST_per = case_when(YEAR_str == "2019" & DAA == "EBR" ~ 25982.5,
                              .default = COST_per))

df_ebr_imp
```


```{r}
# add DAA

df_ebr_imp <- df_ebr_imp %>%
  left_join(df_daa_dem_total %>%
              filter(DAA == "EBR") %>%
              select(DAA,
                     starts_with("CLASS"),
                     starts_with("DRUG")) %>%
              distinct(, .keep_all = TRUE),
            by = join_by(DAA))

df_ebr_imp
```


```{r}
# overwrite ID
df_ebr_imp <- df_ebr_imp %>%
  mutate(ID = str_c(SHEET, YEAR_str, DAA))
```

```{r}
# override 

df_daa_dem_total <- df_daa_dem_total %>%
  mutate(ID = str_c(SHEET, YEAR_str, DAA) )
```

```{r}
df_daa_dem_total %>% filter(ID %in% df_ebr_imp$ID)

df_daa_dem_total %>% filter(! ID %in% df_ebr_imp$ID)
```

```{r}
df_daa_dem_total <- df_daa_dem_total %>%
  bind_rows(df_ebr_imp) %>%
  select(!ID)
```

```{r}
# aggregate combination therapy

df_daa_dem_total <- df_daa_dem_total %>%
  mutate(DAA_ind = DAA) %>%
  mutate(DAA = case_when(DAA %in% c("DCV", "ASV") ~ "DCV/ASV",
                         DAA %in% c("EBR", "GZR") ~ "EBR/GZR",
                         .default = DAA))
```

```{r}
df_daa_dem_total <- df_daa_dem_total %>%
  mutate(DAA = factor(DAA, levels = c("DCV/ASV",
                                      "SOF/LDV",
                                      "SOF",
                                      "OBV/PTV/r",
                                      "EBR/GZR",
                                      "GLE/PIB",
                                      "SOF/VEL")))
```


```{r}
df_daa_dem_total <- df_daa_dem_total %>%
  mutate(COST_total = COST_per * TOTAL) %>%
  mutate(COST_ind = COST_per * VALUE)
```

```{r}
# total single bar chart

df_daa_dem_total %>% 
  group_by(CLASS_code, DAA) %>%
  summarise(SUM = sum(COST_total)/10^9) %>%
  ggplot(aes( SUM, CLASS_code, fill = DAA)) +
  geom_col()+
  scale_x_continuous(expand = c(0, 0),
                     limits = c(0, 1200),
                     breaks = seq(0, 1200, 200))+
  labs(y = "CLASS",
       x = "Total cost (billion $)")+
  theme_classic()
```

```{r}
# pie chart for visualising proportions

df_daa_dem_total %>% 
  group_by(CLASS_code, DAA) %>%
  summarise(SUM = sum(COST_total)/10^9) %>%
  ggplot(aes(x = "" , y = SUM, fill = DAA)) +
  geom_bar(stat = "identity", width = 1, colour = "white")+
  coord_polar("y", start=0)+
  theme_void()+
  scale_fill_brewer(palette="Set2")
```

```{r}
# 

df_daa_dem_total %>% 
  group_by(DAA) %>%
  summarise(SUM = sum(COST_total)/10^9) %>%
  ggplot(aes(fct_reorder(DAA, SUM), SUM, fill = DAA)) +
  geom_col()+
  labs(x = "Year",
       y = "Total cost (billion JPY)")+
  theme_classic()
```

```{r}
# horiontal

df_daa_dem_total %>% 
  group_by(DAA) %>%
  summarise(SUM = sum(COST_total)/10^9) %>%
  ggplot(aes(SUM, fct_reorder(DAA, SUM), fill = DAA)) +
  geom_col(width = 0.7)+
  scale_x_continuous(expand = c(0, 0),
                     breaks = seq(0, 500, 100),
                     limits = c(0, 500)) +
  labs(x = "Year",
       y = "Total cost (billion JPY)")+
  theme_classic()+
  theme(axis.title = element_text(size = 8, colour = "black", face = "bold"),
        axis.text = element_text(size = 8, colour = "black"),
        legend.position = "none")

```

```{r}
df_daa_dem_total %>% count(DAA)
```

```{r}
df_daa_dem_total %>% 
  group_by(DAA) %>%
  summarise(SUM = sum(COST_total)/10^9) %>%
  mutate(TOTAL = sum(SUM)) %>%
  mutate(PCT = SUM/TOTAL * 100)
```

```{r}
# total DAA cost in JPY
df_daa_dem_total %>% 
  left_join(df_boj %>% select(YEAR, USD_JPY),
            by=join_by(YEAR_str == YEAR)) %>%
#  mutate(COST_usd = COST_total/USD_JPY) %>%
#  group_by(DAA) %>%
  summarise(SUM = sum(COST_total)/10^9) 
```


```{r}
# total DAA cost in USD

df_daa_dem_total %>% 
  left_join(df_boj %>% select(YEAR, USD_JPY),
            by=join_by(YEAR_str == YEAR)) %>%
  mutate(COST_usd = COST_total/USD_JPY) %>%
#  group_by(DAA) %>%
  summarise(SUM = sum(COST_usd)/10^9) 
```


```{r}
p1_c <- df_daa_dem_total %>% 
  group_by(DAA) %>%
  summarise(SUM = sum(COST_total)/10^9) %>%
  mutate(TOTAL = sum(SUM)) %>%
  mutate(PCT = SUM/TOTAL * 100) %>%
  mutate(LABEL = paste0(round(PCT), "%")) %>%
  mutate(LABEL = case_when(DAA == "SOF/VEL" ~ "0.4%",
                           .default = LABEL)) %>%
  ggplot(aes(SUM, fct_reorder(DAA, SUM), fill = DAA)) +
  geom_col(width = 0.6)+
  scale_fill_manual(values = c("#0072B2",
                               "#CC79A7",
                               "#56BE49",
                              "#D55E00",
                              "#009E73",
                              "#E69F00",
                         "grey60"))+
  geom_text(aes(x = SUM+5, label = LABEL), size = 2.8, hjust = 0)+
  scale_x_continuous(expand = c(0, 0),
                     breaks = c(seq(0, 500, 100), 50 ),
                     limits = c(0, 500),
                     label = label_number()) +
  coord_cartesian(clip = "off")+
  labs(tag = "C",
       x = "<b>Total cost (10<sup>9</sup> JPY)</b>",
       y = "<b>DAA</b>")+
  theme_classic()+
  theme(plot.tag = element_text(size = 12, colour = "black", face = "bold"),,
        axis.title.x = element_markdown(size = 8, colour = "black"),
        axis.title.y = element_markdown(size = 8, colour = "black"),
        axis.text = element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"),
        legend.position = "none",
        legend.title = element_text(size = 8, colour = "black", face = "bold"),
        legend.text = element_text(size = 8, colour = "black"),
        plot.margin = margin(0,0,0,0,unit =  "mm"))

p1_c
```



```{r}
df_daa_dem_total %>%
  distinct(DAA_ind, YEAR_str, SHEET, .keep_all = TRUE) %>%
  group_by(DAA, YEAR_str) %>%
  summarise(SUM = sum(COST_total)/10^9) %>%  
   ggplot(aes(YEAR_str, SUM)) +
  geom_col(width = 0.7)+
    scale_y_continuous(expand = c(0, 0),
                     breaks = seq(0, 500, 100),
                     limits = c(0, 500)) +
  labs(x = "Year",
       y = "Total cost (billion JPY)")+
  theme_classic()+
   theme(axis.title = element_text(size = 8, colour = "black", face = "bold"),
        axis.text = element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"),
        legend.position = "right",
        legend.title = element_text(size = 8, colour = "black", face = "bold"),
        legend.text = element_text(size = 8, colour = "black"))
```


```{r}
df_daa_dem_total %>%
  distinct(DAA_ind, YEAR_str, SHEET, .keep_all = TRUE) %>%
  ungroup() %>%
  group_by(DAA, YEAR_str) %>%
  summarise(SUM = sum(COST_total)/10^9) %>%  
  mutate(DAA = factor(DAA, levels = c("OBV/PTV/r",
                                      "EBR/GZR",
                                      "SOF/VEL",
                                      "DCV/ASV",
                                      "SOF",
                                      "SOF/LDV",
                                      "GLE/PIB"))) %>%
  ggplot(aes(YEAR_str, SUM, fill = DAA)) +
  geom_col(width = 0.7)+
    scale_fill_manual(values = c("#D55E00",
                                  "#009E73",
                                 "grey60",
                                 "#0072B2",
                               "#56BE49",
                               "#CC79A7",
                             
                              "#E69F00"))+
    scale_y_continuous(expand = c(0, 0),
                     breaks = seq(0, 500, 100),
                     limits = c(0, 500)) +
  labs(x = "Year",
       y = "Total cost (billion JPY)")+
  theme_classic()+
   theme(axis.title = element_text(size = 8, colour = "black", face = "bold"),
        axis.text = element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"),
        legend.position = "right",
        legend.title = element_text(size = 8, colour = "black", face = "bold"),
        legend.text = element_text(size = 8, colour = "black"))
```

```{r}
df_daa_dem_all <- df_daa_dem_total %>%
  distinct(DAA_ind, YEAR_str, SHEET, .keep_all = TRUE) %>%
  ungroup() %>%
  group_by(YEAR_str) %>%
  summarise(SUM = sum(COST_total)/10^9) %>%
  mutate(DAA = "Total")

df_daa_dem_all
```


```{r}
df_daa_dem_total %>%
  distinct(DAA_ind, YEAR_str, SHEET, .keep_all = TRUE) %>%
  ungroup() %>%
  group_by(DAA, YEAR_str) %>%
  summarise(SUM = sum(COST_total)/10^9) %>%  
  bind_rows(df_daa_dem_all) %>%
  mutate(DAA = factor(DAA, levels = c("Total",
                                      "DCV/ASV",
                                      "SOF",
                                      "SOF/LDV",
                                      "OBV/PTV/r",
                                      "EBR/GZR",
                                      "GLE/PIB",
                                      "SOF/VEL"))) %>%
  ggplot(aes(YEAR_str, SUM, group = DAA, colour = DAA)) +
  geom_point(size = 1)+
  geom_line(linewidth = 0.5)+
    scale_colour_manual(values = c("black",
                                 "#0072B2",
                               "#56BE49",
                               "#CC79A7",
                              "#D55E00",
                              "#009E73",
                              "#E69F00",
                         "grey"))+
    scale_y_continuous(expand = c(0, 0),
                     breaks = seq(0, 500, 100),
                     limits = c(0, 500)) +
  labs(x = "Year",
       y = "Total cost (billion $)")+
  theme_classic()+
   theme(axis.title = element_text(size = 8, colour = "black", face = "bold"),
        axis.text = element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"),
        legend.position = "right",
        legend.title = element_text(size = 8, colour = "black", face = "bold"),
        legend.text = element_text(size = 8, colour = "black"))
```

```{r}
cs_cost_max <- df_daa_dem_total %>%
  distinct(DAA_ind, YEAR_str, SHEET, .keep_all = TRUE) %>%
  ungroup() %>%
  group_by(YEAR_str) %>%
  summarise(SUM = sum(COST_total)/10^9) %>%
  ungroup() %>%
  mutate(CS = cumsum(SUM)) %>%
  filter(CS == max(CS)) %>% pull(CS)

cs_cost_max
```

```{r}
df_daa_dem_cost_all <- df_daa_dem_total %>%
  distinct(DRUG_name, YEAR_str, SHEET, .keep_all = TRUE) %>%
  ungroup() %>%
  group_by(YEAR_str) %>%
  summarise(SUM = sum(COST_total)/10^9)

df_daa_dem_cost_all
```


```{r}
df_daa_dem_total %>%
  distinct(DRUG_name, YEAR_str, SHEET, .keep_all = TRUE) %>%
  ungroup() %>%
  group_by(YEAR_str) %>%
  summarise(SUM = sum(COST_total)/10^9) %>%
  left_join(df_boj, by = join_by(YEAR_str == YEAR) ) %>%
  mutate(SUM_usd = SUM/USD_JPY) %>%
  relocate(SUM_usd, .after= "SUM")
```


```{r}
p1_a1 <- df_daa_dem_cost_all %>%
  mutate(DAA = "Annual") %>%
    mutate(YEAR_str = as.numeric(YEAR_str)) %>%
  ggplot(aes(YEAR_str, SUM, group = DAA))+
  geom_line(linewidth = 0.3)+
  geom_point(size = 1)+
   scale_x_continuous(breaks = seq(2014, 2023, 2),
                     limits = c(2014, 2023))+
  scale_y_continuous(# expand = c(0, 0),
                     breaks = c(seq(0, 500, 100)),
                     limits = c(0, 500),
                     label = label_comma()) +
  geom_text(data = df_daa_dem_cost_all %>%
                  filter(YEAR_str == "2015") %>%
                  mutate(label = scales::comma(round(SUM))) %>%
                  mutate(YEAR_str = as.numeric(YEAR_str)),
                aes(x = YEAR_str, y = SUM + 500/20, label = label),
                vjust = 0,
                size = 2.8,
                colour = "black",
                inherit.aes = FALSE)+
      annotate(geom = "text",
           x = (2014 + 2023)/2,
           y = 500,
           vjust = 0.5,
           label = "Annual",
           size = 2.8,
           colour = "black",
           fontface = "bold")+
  coord_cartesian(clip = "off")+
    labs(tag = "A",
         x = "<b>Year</b>",
         y = "<b>Cost (10<sup>9</sup> JPY)</b>")+
  theme_classic()+
  theme(legend.position = "right")+
    theme(plot.tag = element_text(size = 12, colour = "black", face = "bold"),
         axis.title.x = element_markdown(size = 8, colour = "black"),
         axis.title.y = element_markdown(size = 8, colour = "black"),
        axis.text.x = element_text(size = 8, colour = "black"),
        axis.text.y = element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"),
        legend.position = "none",
        legend.title = element_blank(),
        legend.text = element_text(size = 8, colour = "black"),
        legend.spacing.y = unit(0, unit ="mm"),
        legend.background = element_blank(),
      plot.margin = margin(0,0,0,0, "mm"))

p1_a1
```


```{r}
p1_a2 <-  df_daa_dem_cost_all %>%
  mutate(CUMSUM = cumsum(SUM)/10^3) %>%
  mutate(DAA = "Cumulative") %>%
  mutate(YEAR_str = as.numeric(YEAR_str)) %>%
  ggplot(aes(YEAR_str, CUMSUM, group= DAA))+
  geom_line(linewidth = 0.3)+
  geom_point(size = 1)+
  geom_text(data = df_daa_dem_cost_all %>%
                  mutate(CUMSUM = cumsum(SUM)/10^3) %>%
                  filter(YEAR_str == "2023") %>%
                  mutate(label = round(CUMSUM, digits = 2),
                         YEAR_str = as.numeric(YEAR_str)),
                aes(x = YEAR_str, y = CUMSUM +1.5/20 , label = label),
                 vjust = 0,
            hjust = 0.5,
                size = 2.8,
                colour = "black",
                inherit.aes = FALSE)+
    annotate(geom = "text",
           x = (2014 + 2023)/2,
           y = 1.5,
           vjust =0.5,
           label = "Cumulative",
           size = 2.8,
           colour = "black",
           fontface = "bold")+
    scale_x_continuous(breaks = seq(2014, 2023, 2),
                     limits = c(2014, 2023))+
      scale_y_continuous(#expand = c(0, 0),
                     breaks = c(seq(0, 1.5, 0.5)),
                     limits = c(0, 1.5),
                     label = label_comma()) +
  coord_cartesian(clip = "off")+
    labs(
         x = "<b>Year</b>",
         y = "<b>Cost (10<sup>12</sup> JPY)</b>")+
  theme_classic()+
    theme(
         axis.title.x = element_markdown(size = 8, colour = "black"),
         axis.title.y = element_markdown(size = 8, colour = "black"),
         axis.text.x = element_text(size = 8, colour = "black"),
        axis.text.y = element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"),
        legend.position = "none",
        legend.title = element_blank(),
        legend.text = element_text(size = 8, colour = "black"),
        legend.spacing.y = unit(0, unit ="mm"),
        legend.background =element_blank(),
      plot.margin = margin(0,0,0,0, "mm"))

p1_a2
```

```{r}
df_cost_all %>%
  filter(as.numeric(YEAR) >= 2014) %>%
  mutate(TYPE = "All") %>%
  mutate(COST = COST/10) %>%
  ggplot(aes(YEAR, COST, group = TYPE)) +
  geom_line(linewidth = 0.3)+
  geom_point()+
  scale_y_continuous(breaks = seq(0, 50000, 10000),
                     limits = c(0, 50000))+
  labs(x = "Healthcare cost\n(x10)",
       y = "Year")+
  theme_classic()+
  theme(plot.tag = element_text(size = 12, colour = "black", face = "bold"),
         axis.title = element_text(size = 8, colour = "black", face = "bold"),
        axis.text = element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"),
        legend.position = "right",
        legend.title = element_blank(),
        legend.text = element_text(size = 8, colour = "black"),
        legend.spacing.y = unit(0, unit ="mm"),
        legend.background =element_blank(),
      plot.margin = unit(c(0, 0, 0, 0), "mm"))
```



```{r}
df_cost_all %>%
               mutate(YEAR_p = as.numeric(YEAR) -1) %>%
               mutate(YEAR_id = paste0(YEAR, "_", YEAR_p)) %>%
               mutate(COST_diff = COST - lag(COST))
```


```{r}
df_cost_all_diff <- df_cost_all %>%
  filter(as.numeric(YEAR)>= 2014) %>%
               mutate(YEAR_p = as.numeric(YEAR) -1) %>%
               mutate(COST_diff = COST - lag(COST)) %>%
  select(!YEAR_p) %>%
  filter(!is.na(COST_diff)) %>%
  mutate(COST_diff = COST_diff/10)
```

```{r}
df_cost_all_diff %>%
  ggplot(aes(YEAR, COST_diff)) +
  geom_col(width = 0.7)+
  theme_classic()+
  theme(axis.text.x = element_text(size = 8, colour = "black"))
```

```{r}
df_daa_dem_all %>%
  mutate(YEAR_p = as.numeric(YEAR_str) -1) %>%
  mutate(SUM_diff = SUM - lag(SUM)) %>%
  filter(YEAR_str != "2014") %>%
  left_join( df_cost_all_diff ,
             by = join_by(YEAR_str == YEAR)
  )
```


```{r}
df_daa_dem_diff <- df_daa_dem_all %>%
  mutate(SUM_diff = SUM - lag(SUM)) %>%
  filter(YEAR_str != "2014") %>%
  left_join( df_cost_all_diff ,
             by = join_by(YEAR_str == YEAR)
  )

df_daa_dem_diff
```

```{r}
df_daa_dem_diff  <- df_daa_dem_diff %>%
  mutate(DAA = if_else(COST_diff > 0, "p", "n")) %>%
  bind_rows(df_daa_dem_diff %>%
              select(!SUM_diff) %>%
              rename(SUM_diff = "COST_diff") %>%
              mutate(DAA = "t")) %>%
  mutate(DAA = factor(DAA, levels = c("t", "p", "n")))
```



```{r}
df_daa_dem_diff %>%
   mutate(RTO = SUM_diff/COST_diff * 100) %>%
  mutate(RTO = round(RTO)) %>%
  mutate(RTO = paste0(RTO, "%")) %>%
  mutate(YP = case_when(YEAR_str %in%  c("2015", "2016") & DAA != "t" ~ SUM_diff/2,
                        .default = NA), vjust = 0.5) %>%
  ggplot()+
  geom_col(aes(YEAR_str, SUM_diff, fill = DAA), width = 0.7)+
  scale_fill_manual(values= c("grey",
                              "#D55E00",
                              "#0072B2" ),
                    breaks = c("Total cost change",
                               "DAA cost increase",
                               "DAA cost decrease"))+
  geom_text(aes(x = YEAR_str, y = YP, label = RTO, colour = PN),
            size = 2.8, colour = "white")+
  geom_hline(yintercept = 0, linewidth = 0.3, colour = "black")+
  scale_y_continuous(expand = c(0, 0),
                     breaks = seq(-1500, 2500, 500),
                     limits = c(-1500, 2500),
                     label = label_comma())+
  labs(tag = "c",
       x = "Year",
       y = "Cost change from previous year\n(billion JPY)")+
  theme_classic()+
  theme(plot.tag = element_text(size = 12, colour = "black", face = "bold"),
        axis.title = element_text(size = 8, colour = "black", face = "bold"),
        axis.text = element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"),
        legend.position = "right",
        plot.margin = margin(0, 0, 0, 0, "mm"))

```


```{r}
p1_b <- df_daa_dem_all %>%
  mutate(YEAR_p = as.numeric(YEAR_str) -1) %>%
  mutate(SUM_diff = SUM - lag(SUM)) %>%
  filter(! YEAR_str %in% c("2014")) %>%
  left_join( df_cost_all_diff ,
             by = join_by(YEAR_str == YEAR) ) %>%
  mutate(RTO = SUM_diff/COST_diff * 100) %>%
  mutate(RTO = round(RTO)) %>%
  mutate(RTO = paste0(RTO, "%")) %>%
  mutate(YP = case_when(YEAR_str %in%  c("2015", "2016") ~ SUM_diff/2,
                        .default = NA), vjust = 0.5) %>%
  mutate(EX = case_when( (SUM_diff >0 & COST_diff >0) |
                           (SUM_diff < 0 & COST_diff <0)
                           ~ COST_diff - SUM_diff,
                         .default = COST_diff)) %>%
  pivot_longer(cols = c(SUM_diff, EX),
               names_to = "CC",
               values_to = "VALUE") %>%
  mutate(CAT = case_when(CC == "SUM_diff" & VALUE>0 ~ "DAA increase",
                         CC == "SUM_diff" & VALUE <0 ~ "DAA decrease",
                         CC == "EX" ~ "Total change")) %>%
  mutate(CAT = factor(CAT, levels = c("Total change",
                                      "DAA increase",
                                      "DAA decrease"))) %>%
  ggplot(aes(YEAR_str, VALUE, fill = CAT))+
  geom_col(width = 0.6, position = "stack")+
    scale_fill_manual(values= c("gray60",
                                "#D55E00",
                              "#0072B2" ),
                      name = "Healthcare cost")+
  geom_hline(yintercept = 0, linewidth = 0.3, colour = "black")+
  geom_text(aes(x = YEAR_str, y = YP, label = RTO, colour = PN),
            size = 2.8, colour = "white")+
  scale_y_continuous(expand = c(0, 0),
                     breaks = seq(-1500, 2500, 500),
                     limits = c(-1500, 2500),
                     label = label_comma())+
  labs(tag = "B",
       x = "Year",
       y = "Change from prior year<br>(10<sup>9</sup> JPY)")+
  theme_classic()+
  theme(plot.tag = element_text(size = 12, colour = "black", face = "bold"),
        axis.title.x = element_markdown(size = 8, colour = "black", face = "bold"),
        axis.title.y = element_markdown(size = 8, colour = "black", face = "bold", lineheight = 1.2),
        axis.text = element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"),
        legend.position = "right",
        legend.justification = "left",
        legend.title = element_text(size = 8, colour = "black", face = "bold"),
        legend.text = element_text(size = 8, colour = "black"),
        legend.background = element_blank(),
        legend.key.size = unit(5, "mm"),
         plot.margin = margin(0, 0, 0, 0, unit = "mm"),
        legend.margin = margin(0, 0, 0, 0, unit = "mm"))
       # legend.box.margin = margin(0, 0, 0, 0, unit = "mm"))

p1_b 
```



```{r}
df_daa_dem_all %>%
  mutate(YEAR_p = as.numeric(YEAR_str) -1) %>%
  mutate(SUM_diff = SUM - lag(SUM)) %>%
  filter(! YEAR_str %in% c("2014", "2023")) %>%
  left_join( df_cost_all_diff ,
             by = join_by(YEAR_str == YEAR) ) %>%
  mutate(RTO = SUM_diff/COST_diff * 100) %>%
  mutate(PN = if_else(SUM_diff >0, "p", "n")) %>%
  mutate(PN = factor(PN, levels = c("p", "n"))) %>%
  mutate(RTO = SUM_diff/COST_diff * 100) %>%
  mutate(RTO = round(RTO)) %>%
  mutate(RTO = paste0(RTO, "%")) %>%
  mutate(YP = case_when(YEAR_str %in%  c("2015", "2016") ~ SUM_diff/2,
                        .default = NA), vjust = 0.5) %>%
  ggplot()+
  geom_col(aes(YEAR_str, COST_diff), fill = "grey", width = 0.6)+
  geom_col(aes(YEAR_str, SUM_diff, fill = PN), width = 0.6)+
  scale_fill_manual(values= c("#D55E00",
                              "#0072B2" ))+
  geom_hline(yintercept = 0, linewidth = 0.3, colour = "black")+
  geom_text(aes(x = YEAR_str, y = YP, label = RTO, colour = PN),
            size = 2.8, colour = "white")+
  scale_y_continuous(expand = c(0, 0),
                     breaks = seq(-1500, 2500, 500),
                     limits = c(-1500, 2500),
                     label = label_comma())+
  labs(tag = "B",
       x = "Year",
       y = "Cost change from prior year<br>(10<sup>9</sup> JPY)")+
  theme_classic()+
  theme(plot.tag = element_text(size = 12, colour = "black", face = "bold"),
        axis.title = element_markdown(size = 8, colour = "black", face = "bold"),
        axis.text = element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"),
        legend.position = "none",
        plot.margin = margin(0, 0, 0, 0, "mm"))
```



```{r}
p1_d <- df_daa_dem_total %>%
  distinct(DAA_ind, YEAR_str, SHEET, .keep_all = TRUE) %>%
  ungroup() %>%
  group_by(DAA, YEAR_str) %>%
  summarise(SUM = sum(COST_total)/10^9) %>%  
  mutate(YEAR_str = as.numeric(YEAR_str)) %>%
  mutate(DAA = factor(DAA, levels = c(
                                      "DCV/ASV",
                                      "SOF/LDV",
                                      "SOF",
                                      "OBV/PTV/r",
                                      "EBR/GZR",
                                      "GLE/PIB",
                                      "SOF/VEL"))) %>%
  ggplot(aes(YEAR_str, SUM, group = DAA, colour = DAA)) +
  geom_line(linewidth = 0.3)+
  geom_point(size = 1)+
    scale_colour_manual(values = c(
                                 "#0072B2",
                               
                               "#CC79A7",
                               "#56BE49",
                              "#D55E00",
                              "#009E73",
                              "#E69F00",
                         "grey60"))+
        annotate(geom = "text",
           x = (2014 + 2023)/2,
           y = 250,
           label = "Annual",
           size = 2.8,
           colour = "black",
           fontface = "bold")+
      scale_x_continuous(
                     breaks = seq(2014, 2023, 1),
                     limits = c(2014, 2023)) +
    scale_y_continuous(
                     breaks = seq(0, 250, 50),
                     limits = c(0, 250),
                     label = label_number()) +
  labs(tag = "D",
       x = "<b>Year</b>",
       y = "<b>Cost (10<sup>9</sup> JPY)</b>")+
  theme_classic()+
   theme(plot.tag = element_text(size = 12, colour = "black", face = "bold"),
         axis.title.x = element_markdown(size = 8, colour = "black"),
         axis.title.y = element_markdown(size = 8, colour = "black"),
        axis.text = element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"),
        legend.position = "right",
        legend.title = element_text(size = 8, colour = "black", face = "bold"),
        legend.text = element_text(size = 8, colour = "black"),
        legend.background = element_blank(),
        legend.margin = margin(0, 0, 0, 0, "mm"))
       # plot.margin = margin(0, 0, 0, 0, "mm"))

p1_d
```

```{r}
df_daa_dem_total %>%
  distinct(DAA_ind, YEAR_str, SHEET, .keep_all = TRUE) %>%
  ungroup() %>%
  group_by(DAA, YEAR_str) %>%
  summarise(SUM = sum(COST_total)/10^9) %>%  
  ungroup() %>%
  group_by(DAA) %>%
  mutate(CUMSUM = cumsum(SUM)) 
```


```{r}
p1_e <- df_daa_dem_total %>%
  distinct(DAA_ind, YEAR_str, SHEET, .keep_all = TRUE) %>%
  ungroup() %>%
  group_by(DAA, YEAR_str) %>%
  summarise(SUM = sum(COST_total)/10^9) %>%  
  ungroup() %>%
  group_by(DAA) %>%
  mutate(CUMSUM = cumsum(SUM)) %>%
  mutate(YEAR_str = as.numeric(YEAR_str)) %>%
  ggplot(aes(YEAR_str, CUMSUM, group= DAA, colour = DAA))+
  geom_line(linewidth = 0.3)+
  geom_point(size = 1)+
  scale_colour_manual(values = c( "#0072B2",
                              
                               "#CC79A7",
                                "#56BE49",
                              "#D55E00",
                              "#009E73",
                              "#E69F00",
                              "grey60"))+
      annotate(geom = "text",
           x = (2014 + 2023)/2,
           y = 500,
           label = "Cumulative",
           size = 2.8,
           colour = "black",
           fontface = "bold")+
        scale_x_continuous(
                     breaks = seq(2014, 2023, 1),
                     limits = c(2014, 2023)) +
      scale_y_continuous(
                     breaks = c(seq(0, 500, 100)),
                     limits = c(0, 500),
                     label = label_number()) +
    labs(tag = "E",
         x = "<b>Year</b>",
       y = "<b>Cost (10<sup>9</sup> JPY)<b>")+
  theme_classic()+
  theme(legend.position = "right")+
    theme(plot.tag = element_text(size = 12, colour = "black", face = "bold"),
          axis.title.x = element_markdown(size = 8, colour = "black"),
          axis.title.y = element_markdown(size = 8, colour = "black"),
        axis.text = element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"),
        legend.position = "right",
        legend.justification = "left",
        legend.title = element_text(size = 8, colour = "black", face = "bold"),
        legend.text = element_text(size = 8, colour = "black"),
        legend.background = element_blank(),
        plot.margin = margin(0, 0, 0, 0, unit = "mm"),
        legend.margin = margin(0, 0, 0, 0, unit = "mm"))
        #legend.box.margin = margin(0, 0, 0, 0, unit = "mm"))

p1_e
```


```{r}
p1_a <- p1_a1 + plot_spacer()+ p1_a2 +
  plot_layout(widths = c(1, 1/100, 1 ))

p1_a 
```



```{r}
p1 <- free(p1_a, side = "l", type = "label") + 
  free(p1_b, side = "l", type = "label") + 
  free(p1_c, side = "l", type = "label") + 
  free(p1_d, side = "l", type = "label") + 
  plot_layout(height = c(2, 2, 2, 3)) &
  theme(legend.justification = "left")
  
ggsave("../figure/Fig2.pdf", plot = p1, width = 180, height = 235, unit = "mm")

#ggsave("../figure/Fig2.jpg", plot = p1, width = 180, height = 235, unit = "mm",
#       dpi = 450)
```


```{r}
# save df_daa_dem_total
saveRDS(df_daa_dem_total, "../df/daa/analysis/df_daa_dem_total")
```

