---
title: "HCV DAA"
output: html_document
date: "2025-11-20"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readxl)
library(openxlsx)

library(broom)
library(ggrepel)
```

```{r}
df_daa_dem <- readRDS("../df/daa/format/df_daa_dem")
```


# df_daa_dem

```{r}
df_daa_dem %>% count(DAA)
```


```{r}
df_daa_dem %>% count(SHEET)
```

```{r}
df_daa_dem_sa <- df_daa_dem
```

```{r}
# check discordance in combination therapy

df_daa_dem_sa %>% 
  distinct(DAA, AGE, SEX, YEAR_str, SHEET, .keep_all = TRUE) %>%
  filter(DAA %in% c("DCV", "ASV", "EBR", "GZR")) %>%
  count(DAA, YEAR_str)

# DCV/ASV complete pairs
# EBR/GZR needs impution
```

```{r}
df_daa_dem_sa %>% 
  distinct(DAA, SEX_AGE, YEAR_str, SHEET, .keep_all = TRUE) %>%
  filter(DAA %in% c("DCV", "ASV", "EBR", "GZR")) %>%
  count(DAA, YEAR_str)
```


```{r}
# check SHEET category in EBR/GZR

df_daa_dem_sa %>% 
  distinct(DAA, YEAR_str, SHEET, .keep_all = TRUE) %>%
  filter(DAA %in% c("EBR", "GZR")) %>%
  count(DAA, YEAR_str)

#1 EBR 2018 1 category missing -> impute from GZR 2018

#2 GZR 2019 1 cateogry missing & EBR 2019 all missing -> impute 2 caterories in EBR from GZR
# unable to fill missing GZR
```


```{r}
df_daa_dem_sa %>% 
  distinct(DAA,SEX_AGE, YEAR_str, SHEET, .keep_all = TRUE) %>%
   filter(DAA %in% c("DCV", "ASV")) %>%
  select(SHEET,  DAA, SEX_AGE, AGE, SEX, VALUE, YEAR_str) %>%
  pivot_wider(names_from = DAA, values_from = VALUE, values_fill = 0) %>% 
  filter( (ASV ==0 & DCV>0) | (ASV >0 & DCV ==0)) %>%
  View()

```

```{r}
df_daa_dem_sa %>% 
  distinct(DAA,SEX_AGE, YEAR_str, SHEET, .keep_all = TRUE) %>%
  filter(DAA %in% c("DCV", "ASV")) %>%
  select(SHEET,  DAA, SEX_AGE, AGE, SEX, VALUE, YEAR_str) %>%
  pivot_wider(names_from = DAA, values_from = VALUE, values_fill = 0) %>% 
  filter( ASV  > 0 & DCV > 0 ) %>%
  mutate(RATIO = ASV/DCV) %>%
  ggplot(aes(SHEET, RATIO))+
  geom_boxplot()+
  geom_point()+
  scale_y_continuous(limits = c(0, 3),
                     breaks = seq(0, 3, 1))+
  theme_classic()
```



```{r}
df_daa_dem_sa %>% 
  distinct(DAA,SEX_AGE, YEAR_str, SHEET, .keep_all = TRUE) %>%
  filter(DAA %in% c("DCV", "ASV")) %>%
  select(SHEET,  DAA, SEX_AGE, VALUE, YEAR_str) %>%
  pivot_wider(names_from = DAA, values_from = VALUE, values_fill = 0) %>% 
  filter( ASV  > 0 & DCV > 0 ) %>%
  mutate(RATIO = ASV/DCV) %>%
  group_by(SHEET) %>%
  summarise(MED = median(RATIO),
            MIN = min(RATIO),
            MAX = max(RATIO))
```



```{r}
df_daa_dem_sa %>% 
  distinct(DAA,SEX_AGE, YEAR_str, SHEET, .keep_all = TRUE) %>%
   filter(DAA %in% c("EBR", "GZR")) %>%
  select(SHEET,  DAA, SEX_AGE, AGE, SEX, VALUE, YEAR_str) %>%
  pivot_wider(names_from = DAA, values_from = VALUE, values_fill = 0) %>% 
  filter( (EBR ==0 & GZR>0) | (EBR >0 & GZR ==0)) %>%
  View()

# GZR >0, EBR = 0
```


```{r}
df_daa_dem_sa %>% 
  distinct(DAA,SEX_AGE, YEAR_str, SHEET, .keep_all = TRUE) %>%
   filter(DAA %in% c("EBR", "GZR")) %>%
  select(SHEET,  DAA, SEX_AGE, AGE, SEX, VALUE, YEAR_str) %>%
  pivot_wider(names_from = DAA, values_from = VALUE, values_fill = 0) %>% 
  filter(EBR != 0) %>%
  mutate(RATIO = GZR/EBR) %>%
  ggplot(aes(SHEET, RATIO))+
  geom_boxplot()+
  geom_point()+
  scale_y_continuous(limits = c(0, 3),
                     breaks = seq(0, 3, 1))+
  theme_classic()
```


```{r}
df_daa_dem_sa %>% 
  distinct(DAA,SEX_AGE, YEAR_str, SHEET, .keep_all = TRUE) %>%
  filter(DAA %in% c("EBR", "GZR")) %>%
  select(SHEET,  DAA, SEX_AGE, VALUE, YEAR_str) %>%
  pivot_wider(names_from = DAA, values_from = VALUE, values_fill = 0) %>% 
   filter(EBR != 0) %>%
  mutate(RATIO = GZR/EBR) %>%
  group_by(SHEET) %>%
  summarise(MED = median(RATIO),
            MIN = min(RATIO),
            MAX = max(RATIO))
```

```{r}
df_daa_dem_sa %>% 
  distinct(DAA,SEX_AGE, YEAR_str, SHEET, .keep_all = TRUE) %>%
   filter(DAA %in% c("DCV", "ASV")) %>%
  select(SHEET,  DAA, SEX_AGE, AGE, SEX, VALUE, YEAR_str) %>%
  pivot_wider(names_from = DAA, values_from = VALUE, values_fill = 0) %>% 
  filter( (ASV ==0 & DCV>0) | (ASV >0 & DCV ==0))
```




```{r}
# fill zero
df_asv_dcv_fill <- df_daa_dem_sa %>% 
  distinct(DAA,SEX_AGE, YEAR_str, SHEET, .keep_all = TRUE) %>%
  filter(DAA %in% c("DCV", "ASV")) %>%
  select(SHEET,  DAA, SEX_AGE, AGE, SEX, VALUE, YEAR_str) %>%
  pivot_wider(names_from = DAA, values_from = VALUE, values_fill = 0) %>% 
  filter( (ASV ==0 & DCV>0) | (ASV >0 & DCV ==0)) %>%
  filter(DCV == 0) %>%
  mutate(DCV = case_when(DCV == 0 ~ ASV/2,
                         .default = DCV))

df_asv_dcv_fill
```

```{r}
df_asv_dcv_long <- df_asv_dcv_fill %>%
  pivot_longer(cols = c(ASV, DCV),
               names_to = "DAA",
               values_to = "VALUE")

df_asv_dcv_long
```


```{r}
# SHEET , YEAR_str, and DAA should give unique ID

df_daa_dem_sa %>% nrow()

df_daa_dem_sa %>%
  mutate(ID = str_c(SHEET, SEX_AGE, YEAR_str, DAA, sep = "_")) %>%
  distinct(ID) %>% nrow()
```


```{r}
# create ID for df_total to get COST_per

df_daa_dem_sa <- df_daa_dem_sa %>%
  mutate(ID = str_c(YEAR_str, DAA, sep = "_")) 
```


```{r}
# create ID for df liong

df_dcv_imp <- df_asv_dcv_long %>%
  filter(DAA == "DCV") %>%
  mutate(ID = str_c(YEAR_str, DAA, sep = "_")) 

df_dcv_imp
```

```{r}
df_dcv_imp <- df_dcv_imp %>%
  left_join(df_daa_dem_sa %>%
              distinct(COST_per, ID), 
            by = join_by(ID))

df_dcv_imp
```



```{r}
# add DAA

df_dcv_imp <- df_dcv_imp %>%
  left_join(df_daa_dem_sa %>%
              filter(DAA == "DCV") %>%
              select(DAA,
                     starts_with("CLASS"),
                     starts_with("DRUG")) %>%
              distinct(, .keep_all = TRUE),
            by = join_by(DAA))

df_dcv_imp
```


```{r}
# overwrite ID
df_dcv_imp <- df_dcv_imp %>%
  mutate(ID = str_c(SHEET, YEAR_str, DAA, SEX_AGE, sep = "_"))
```

```{r}
# override 

df_daa_dem_sa <- df_daa_dem_sa %>%
  mutate(ID = str_c(SHEET, YEAR_str, DAA, SEX_AGE, sep = "_") )
```

```{r}
df_daa_dem_sa %>% filter(ID %in% df_dcv_imp$ID)

df_daa_dem_sa %>% filter(! ID %in% df_dcv_imp$ID)

# all in original df_sa -> row_update
```

```{r}
# row update DCV

df_daa_dem_sa <- df_daa_dem_sa %>%
  rows_update(df_dcv_imp %>% select(VALUE, ID), by = "ID") %>%
  select(!ID)
```

# EBR/GZR

```{r}
df_daa_dem_sa %>% 
  distinct(DAA,SEX_AGE, YEAR_str, SHEET, .keep_all = TRUE) %>%
   filter(DAA %in% c("EBR", "GZR")) %>%
  select(SHEET,  DAA, SEX_AGE, AGE, SEX, VALUE, YEAR_str) %>%
  pivot_wider(names_from = DAA, values_from = VALUE, values_fill = 0) %>% 
  filter( (EBR ==0 & GZR>0) | (EBR >0 & GZR ==0)) %>%
  View()

# all EBR missing
```

```{r}
# fill zero
df_ebr_gzr_fill <- df_daa_dem_sa %>% 
  distinct(DAA,SEX_AGE, YEAR_str, SHEET, .keep_all = TRUE) %>%
  filter(DAA %in% c("EBR", "GZR")) %>%
  select(SHEET,  DAA, SEX_AGE, AGE, SEX, VALUE, YEAR_str) %>%
  pivot_wider(names_from = DAA, values_from = VALUE, values_fill = 0) %>% 
  filter( (EBR ==0 & GZR >0) | (EBR >0 & GZR ==0)) %>%
  filter(EBR == 0) %>%
  mutate(EBR = case_when(EBR == 0 ~ GZR/2,
                         .default = EBR))

df_ebr_gzr_fill
```


```{r}
df_ebr_gzr_long <- df_ebr_gzr_fill %>%
  pivot_longer(cols = c(EBR, GZR),
               names_to = "DAA",
               values_to = "VALUE")

df_ebr_gzr_long
```

```{r}
# create ID for df_total to get COST_per

df_daa_dem_sa <- df_daa_dem_sa %>%
  mutate(ID = str_c(YEAR_str, DAA, sep = "_")) 
```


```{r}
# create ID for df liong

df_ebr_imp <- df_ebr_gzr_long %>%
  filter(DAA == "EBR") %>%
  mutate(ID = str_c(YEAR_str, DAA, sep = "_")) 

df_ebr_imp
```

```{r}
df_ebr_imp <- df_ebr_imp %>%
  left_join(df_daa_dem_sa %>%
              distinct(COST_per, ID), 
            by = join_by(ID))

df_ebr_imp
```



```{r}
# add DAA

df_ebr_imp <- df_ebr_imp %>%
  left_join(df_daa_dem_sa %>%
              filter(DAA == "EBR") %>%
              select(DAA,
                     starts_with("CLASS"),
                     starts_with("DRUG")) %>%
              distinct(, .keep_all = TRUE),
            by = join_by(DAA))

df_ebr_imp
```


```{r}
# overwrite ID
df_ebr_imp <- df_ebr_imp %>%
  mutate(ID = str_c(SHEET, YEAR_str, DAA, SEX_AGE, sep = "_"))
```

```{r}
# override 

df_daa_dem_sa <- df_daa_dem_sa %>%
  mutate(ID = str_c(SHEET, YEAR_str, DAA, SEX_AGE, sep = "_") )
```

```{r}
df_daa_dem_sa %>% filter(ID %in% df_ebr_imp$ID)

df_daa_dem_sa %>% filter(! ID %in% df_dcv_imp$ID)

# all in original df_sa -> row_update
```

```{r}
id_ebr_update <- df_daa_dem_sa %>% filter(ID %in% df_ebr_imp$ID) %>% pull(ID)

id_ebr_update %>% length()
```

# check price for EBR/GZR


```{r}
df_daa_dem_sa %>% filter(DAA == "GZR") %>% distinct(YEAR_str, COST_per) %>% arrange(YEAR_str)
```


```{r}
df_daa_dem_sa %>% filter(DAA == "EBR") %>% distinct(YEAR_str, COST_per)
```


```{r}
df_ebr_imp <- df_ebr_imp %>%
  mutate(COST_per = case_when(YEAR_str == "2019" ~ 25982.5,
                              .default = COST_per))

df_ebr_imp
```


```{r}
id_ebr_bind <- df_ebr_imp %>% filter(! ID %in% id_ebr_update) %>% pull(ID)

id_ebr_bind %>% length()
```

```{r}
# row update
df_daa_dem_sa <- df_daa_dem_sa %>%
  rows_update(df_ebr_imp %>%
               filter(ID %in% id_ebr_update) %>%
               select(ID, VALUE),
             by = "ID")
```


```{r}
# bind rows

df_daa_dem_sa <- df_daa_dem_sa %>%
  bind_rows(df_ebr_imp %>%
               filter(ID %in% id_ebr_bind))
```



# end of cleaning


# aggregate DAAs
```{r}
# aggregate combination therapy

df_daa_dem_sa <- df_daa_dem_sa %>%
  mutate(DAA_ind = DAA) %>%
  mutate(DAA = case_when(DAA %in% c("DCV", "ASV") ~ "DCV/ASV",
                         DAA %in% c("EBR", "GZR") ~ "EBR/GZR",
                         .default = DAA))
```

```{r}
df_daa_dem_sa <- df_daa_dem_sa %>%
  mutate(DAA = factor(DAA, levels = c("DCV/ASV",
                                      "SOF/LDV",
                                      "SOF",
                                      
                                      "OBV/PTV/r",
                                      "EBR/GZR",
                                      "GLE/PIB",
                                      "SOF/VEL")))
```


# format age

```{r}
# all rows distinct
df_daa_dem_sa %>% count(YEAR_str, SHEET, SEX_AGE, DAA_ind) %>% count(n)
```

```{r}
df_daa_dem_sa %>% count(AGE) 
```

```{r}
df_daa_dem_sa <- df_daa_dem_sa %>%
  mutate(COST_total = COST_per * TOTAL) %>%
  mutate(COST_ind = COST_per * VALUE)
```

```{r}
df_daa_dem_sa %>%
  distinct(DAA_ind, YEAR_str, AGE, SEX, SHEET, .keep_all = TRUE) %>%
  ungroup() %>%
  group_by(DAA, YEAR_str, AGE, SEX) %>%
  filter(DAA == "DCV/ASV") %>%
  summarise(SUM = sum(COST_ind)) %>%
  ggplot(aes(AGE, SUM, fill = SEX))+
  geom_col()+
  facet_grid(YEAR_str ~ SEX, scales = "free_y")+
  theme_classic()+
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5))
```

```{r}
df_daa_dem_sa %>%
  distinct(DAA_ind, YEAR_str, AGE, SEX, SHEET, .keep_all = TRUE) %>%
  ungroup() %>%
  filter(DAA == "DCV/ASV" & SEX == "M") %>%
  group_by(YEAR_str, AGE, SEX) %>%
  summarise(SUM = sum(COST_ind)) %>%
  ungroup() %>%
  group_by(YEAR_str) %>%
  arrange(AGE) %>%
  mutate(CUM = cumsum(SUM)) %>%
  mutate(PCT = CUM/sum(SUM)*100) %>%
  mutate(MED = PCT >= 50) %>%
  filter(MED == TRUE) %>%
  slice_head(n = 1)
```

```{r}
df_daa_dem_sa %>%
  distinct(DAA_ind, YEAR_str, AGE, SEX, SHEET, .keep_all = TRUE) %>%
  ungroup() %>%
  filter(DAA == "DCV/ASV" & SEX == "F") %>%
  group_by(YEAR_str, AGE, SEX) %>%
  summarise(SUM = sum(COST_ind)) %>%
  ungroup() %>%
  group_by(YEAR_str) %>%
  arrange(AGE) %>%
  mutate(CUM = cumsum(SUM)) %>%
  mutate(PCT = CUM/sum(SUM)*100) %>%
  mutate(MED = PCT >= 50) %>%
  filter(MED == TRUE) %>%
  slice_head(n = 1)
```

# SOF

```{r}
df_daa_dem_sa %>%
  distinct(DAA_ind, YEAR_str, AGE, SEX, SHEET, .keep_all = TRUE) %>%
  ungroup() %>%
  group_by(DAA, YEAR_str, AGE, SEX) %>%
  filter(DAA == "SOF") %>%
  summarise(SUM = sum(COST_ind)) %>%
  ggplot(aes(AGE, SUM, fill = SEX))+
  geom_col()+
  facet_grid(YEAR_str ~ SEX, scales = "free_y")+
  theme_classic()+
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5))
```

```{r}
df_daa_dem_sa %>%
  distinct(DAA_ind, YEAR_str, AGE, SEX, SHEET, .keep_all = TRUE) %>%
  ungroup() %>%
  filter(DAA == "SOF" & SEX == "M") %>%
  group_by(YEAR_str, AGE, SEX) %>%
  summarise(SUM = sum(COST_ind)) %>%
  ungroup() %>%
  group_by(YEAR_str) %>%
  arrange(AGE) %>%
  mutate(CUM = cumsum(SUM)) %>%
  mutate(PCT = CUM/sum(SUM)*100) %>%
  mutate(MED = PCT >= 50) %>%
  filter(MED == TRUE) %>%
  slice_head(n = 1)
```

```{r}
df_daa_dem_sa %>%
  distinct(DAA_ind, YEAR_str, AGE, SEX, SHEET, .keep_all = TRUE) %>%
  ungroup() %>%
  filter(DAA == "SOF" & SEX == "F") %>%
  group_by(YEAR_str, AGE, SEX) %>%
  summarise(SUM = sum(COST_ind)) %>%
  ungroup() %>%
  group_by(YEAR_str) %>%
  arrange(AGE) %>%
  mutate(CUM = cumsum(SUM)) %>%
  mutate(PCT = CUM/sum(SUM)*100) %>%
  mutate(MED = PCT >= 50) %>%
  filter(MED == TRUE) %>%
  slice_head(n = 1)
```


# SOF/LDV

```{r}
df_daa_dem_sa %>%
  distinct(DAA_ind, YEAR_str, AGE, SEX, SHEET, .keep_all = TRUE) %>%
  ungroup() %>%
  group_by(DAA, YEAR_str, AGE, SEX) %>%
  filter(DAA == "SOF/LDV") %>%
  summarise(SUM = sum(COST_ind)) %>%
  ggplot(aes(AGE, SUM, fill = SEX))+
  geom_col()+
  facet_grid(YEAR_str ~ SEX, scales = "free_y")+
  theme_classic()+
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5))
```

```{r}
df_daa_dem_sa %>%
  distinct(DAA, YEAR_str, AGE, SEX, SHEET, .keep_all = TRUE) %>%
  ungroup() %>%
  group_by(DAA, YEAR_str, AGE, SEX) %>%
  filter(DAA == "SOF/LDV") %>%
  summarise(SUM = sum(COST_ind)) %>%
  ggplot(aes(AGE, SUM, group = 1, colour = SEX))+
  geom_line()+
  facet_grid(YEAR_str ~ SEX, scales = "free_y")+
  theme_classic()+
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5))
```

```{r}
df_daa_dem_sa %>%
  distinct(DAA, YEAR_str, AGE, SEX, SHEET, .keep_all = TRUE) %>%
  ungroup() %>%
  filter(DAA == "SOF/LDV" & SEX == "M") %>%
  group_by(YEAR_str, AGE, SEX) %>%
  summarise(SUM = sum(COST_ind)) %>%
  ungroup() %>%
  group_by(YEAR_str) %>%
  filter(SUM == max(SUM))
```

```{r}
df_daa_dem_sa %>%
  distinct(DAA, YEAR_str, AGE, SEX, SHEET, .keep_all = TRUE) %>%
  ungroup() %>%
  filter(DAA == "SOF/LDV" & SEX == "F") %>%
  group_by(YEAR_str, AGE, SEX) %>%
  summarise(SUM = sum(COST_ind)) %>%
  ungroup() %>%
  group_by(YEAR_str) %>%
  filter(SUM == max(SUM))
```

# EBR/GZR

```{r}
df_daa_dem_sa %>%
  distinct(DAA, YEAR_str, AGE, SEX, SHEET, .keep_all = TRUE) %>%
  ungroup() %>%
  group_by(DAA, YEAR_str, AGE, SEX) %>%
  filter(DAA == "EBR/GZR") %>%
  summarise(SUM = sum(COST_ind)) %>%
  ggplot(aes(AGE, SUM, fill = SEX))+
  geom_col()+
  facet_grid(YEAR_str ~ SEX)+
  theme_classic()+
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5))
```

```{r}
df_daa_dem_sa %>%
  distinct(DAA, YEAR_str, AGE, SEX, SHEET, .keep_all = TRUE) %>%
  ungroup() %>%
  group_by(DAA, YEAR_str, AGE, SEX) %>%
  filter(DAA == "EBR/GZR") %>%
  summarise(SUM = sum(COST_ind)) %>%
  ggplot(aes(AGE, SUM, group = 1, colour = SEX))+
  geom_line()+
  facet_grid(YEAR_str ~ SEX, scales = "free_y")+
  theme_classic()+
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5))
```

# GLE/PIB

```{r}
df_daa_dem_sa %>%
  distinct(DAA, YEAR_str, AGE, SEX, SHEET, .keep_all = TRUE) %>%
  ungroup() %>%
  group_by(DAA, YEAR_str, AGE, SEX) %>%
  filter(DAA == "GLE/PIB") %>%
  summarise(SUM = sum(COST_ind)) %>%
  ggplot(aes(AGE, SUM, fill = SEX))+
  geom_col()+
  facet_grid(YEAR_str ~ SEX)+
  theme_classic()+
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5))
```

```{r}
df_daa_dem_sa %>%
  distinct(DAA, YEAR_str, AGE, SEX, SHEET, .keep_all = TRUE) %>%
  ungroup() %>%
  group_by(DAA, YEAR_str, AGE, SEX) %>%
  filter(DAA == "GLE/PIB") %>%
  summarise(SUM = sum(COST_ind)) %>%
  ggplot(aes(AGE, SUM, group = 1, colour = SEX))+
  geom_line()+
  facet_grid(YEAR_str ~ SEX, scales = "free_y")+
  theme_classic()+
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5))
```

```{r}
df_daa_dem_sa %>%
  distinct(DAA, YEAR_str, AGE, SEX, SHEET, .keep_all = TRUE) %>%
  ungroup() %>%
  filter(DAA == "GLE/PIB" & SEX == "M") %>%
  group_by(YEAR_str, AGE, SEX) %>%
  summarise(SUM = sum(COST_ind)) %>%
  ungroup() %>%
  group_by(YEAR_str) %>%
  filter(SUM == max(SUM))
```

```{r}
df_daa_dem_sa %>%
  distinct(DAA, YEAR_str, AGE, SEX, SHEET, .keep_all = TRUE) %>%
  ungroup() %>%
  filter(DAA == "GLE/PIB" & SEX == "F") %>%
  group_by(YEAR_str, AGE, SEX) %>%
  summarise(SUM = sum(COST_ind)) %>%
  ungroup() %>%
  group_by(YEAR_str) %>%
  filter(SUM == max(SUM))
```


```{r}
df_daa_dem_sa %>%
  distinct(DAA, YEAR_str, AGE, SEX, SHEET, .keep_all = TRUE) %>%
  ungroup() %>%
  filter(DAA == "GLE/PIB" & SEX == "M") %>%
  group_by(YEAR_str, AGE, SEX) %>%
  summarise(SUM = sum(COST_ind)) %>%
  ungroup() %>%
  group_by(YEAR_str) %>%
  arrange(AGE) %>%
  mutate(CUM = cumsum(SUM)) %>%
  mutate(PCT = CUM/sum(SUM)*100) %>%
  mutate(MED = PCT >= 50) %>%
  filter(MED == TRUE) %>%
  slice_head(n = 1)
```

```{r}
df_daa_dem_sa %>%
  distinct(DAA, YEAR_str, AGE, SEX, SHEET, .keep_all = TRUE) %>%
  ungroup() %>%
  filter(DAA == "GLE/PIB" & SEX == "F") %>%
  group_by(YEAR_str, AGE, SEX) %>%
  summarise(SUM = sum(COST_ind)) %>%
  ungroup() %>%
  group_by(YEAR_str) %>%
  arrange(AGE) %>%
  mutate(CUM = cumsum(SUM)) %>%
  mutate(PCT = CUM/sum(SUM)*100) %>%
  mutate(MED = PCT >= 50) %>%
  filter(MED == TRUE) %>%
  slice_head(n = 1)
```

# SOF/VEL

```{r}
df_daa_dem_sa %>%
  distinct(DAA, YEAR_str, AGE, SEX, SHEET, .keep_all = TRUE) %>%
  ungroup() %>%
  group_by(DAA, YEAR_str, AGE, SEX) %>%
  filter(DAA == "SOF/VEL") %>%
  summarise(SUM = sum(COST_ind)) %>% View()
```



```{r}
df_daa_dem_sa %>%
  distinct(DAA, YEAR_str, AGE, SEX, SHEET, .keep_all = TRUE) %>%
  ungroup() %>%
  group_by(DAA, YEAR_str, AGE, SEX) %>%
  filter(DAA == "SOF/VEL") %>%
  summarise(SUM = sum(COST_ind)) %>%
  ggplot(aes(AGE, SUM, fill = SEX))+
  geom_col()+
  facet_grid(YEAR_str ~ SEX, scales = "free_y")+
  theme_classic()+
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5))
```

```{r}
df_daa_dem_sa %>%
  distinct(DAA, YEAR_str, AGE, SEX, SHEET, .keep_all = TRUE) %>%
  ungroup() %>%
  group_by(DAA, YEAR_str, AGE, SEX) %>%
  filter(DAA == "SOF/VEL") %>%
  summarise(SUM = sum(COST_ind)) %>%
  ggplot(aes(AGE, SUM, group = 1, colour = SEX))+
  geom_line()+
  facet_grid(YEAR_str ~ SEX, scales = "free_y")+
  theme_classic()+
  theme(legend.position = "none",
        axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5))
```


```{r}
df_daa_dem_sa %>%
  distinct(DAA, YEAR_str, AGE, SEX, SHEET, .keep_all = TRUE) %>%
  ungroup() %>%
  filter(DAA == "SOF/VEL" & SEX == "M") %>%
  group_by(YEAR_str, AGE, SEX) %>%
  summarise(SUM = sum(COST_ind)) %>%
  ungroup() %>%
  group_by(YEAR_str) %>%
  arrange(AGE) %>%
  mutate(CUM = cumsum(SUM)) %>%
  mutate(PCT = CUM/sum(SUM)*100) %>%
  mutate(MED = PCT >= 50) %>%
  filter(MED == TRUE) %>%
  slice_head(n = 1)
```

```{r}
df_daa_dem_sa %>%
  distinct(DAA, YEAR_str, AGE, SEX, SHEET, .keep_all = TRUE) %>%
  ungroup() %>%
  filter(DAA == "GLE/PIB" & SEX == "F") %>%
  group_by(YEAR_str, AGE, SEX) %>%
  summarise(SUM = sum(COST_ind)) %>%
  ungroup() %>%
  group_by(YEAR_str) %>%
  arrange(AGE) %>%
  mutate(CUM = cumsum(SUM)) %>%
  mutate(PCT = CUM/sum(SUM)*100) %>%
  mutate(MED = PCT >= 50) %>%
  filter(MED == TRUE) %>%
  slice_head(n = 1)
```


```{r}
saveRDS(df_daa_dem_sa, "../df/daa/analysis/df_daa_dem_sa")
```

# end of run
