---
title: "HCV DAA"
output: html_document
date: "2025-11-20"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readxl)
library(openxlsx)

library(broom)

library(ggtext)

library(cowplot)
library(patchwork)
library(scales)

library(ggh4x)
library(pals)

```

```{r}
df_daa_dem <- readRDS("../df/daa/format/df_daa_dem")
```

# df_daa_dem

# df_dem_daa
```{r}
df_daa_dem_pts <- df_daa_dem %>%
  mutate(DAA_ind = DAA) %>%
  mutate(DAA = case_when(DAA %in% c("DCV", "ASV") ~ "DCV/ASV",
                         DAA %in% c("EBR", "GZR") ~ "EBR/GZR",
                         .default = DAA))
  
```


```{r}
df_daa_dem_pts <- df_daa_dem_pts %>%
  mutate(DAA = factor(DAA, levels = c("DCV/ASV",
                                      "SOF/LDV",
                                      "SOF",
                                      "OBV/PTV/r",
                                      "EBR/GZR",
                                      "GLE/PIB",
                                      "SOF/VEL")))
```


```{r}
# remove dcv ebr
df_daa_dem_pts <- df_daa_dem_pts %>%
  filter(!DAA_ind %in% c("DCV", "EBR"))
```


```{r}
# calculate min pts by dividing by max duration

df_daa_dem_pts <- df_daa_dem_pts %>%
  mutate(PTS_min = case_when(DAA == "DCV/ASV" ~ VALUE/(168*2),
                             DAA == "EBR/GZR" ~ VALUE/(84*2),
                             DAA %in% c(
                                        "OBV/PTV/r",
                                        "SOF",
                                        "SOF/LDV") ~VALUE/84,
                             DAA == "GLE/PIB" ~ VALUE/(84*3),
                             DAA == "SOF/VEL" ~ VALUE/168))

```

```{r}
# calculate mx pts by dividing min duration

df_daa_dem_pts <- df_daa_dem_pts %>%
  mutate(PTS_max = case_when(DAA == "DCV/ASV" ~ VALUE/(168*2),
                             DAA == "EBR/GZR" ~ VALUE/(84*2),
                             DAA %in% c(
                                        "OBV/PTV/r",
                                        "SOF",
                                        "SOF/LDV") ~ VALUE/84,
                             DAA == "GLE/PIB" ~ VALUE/(56*3),
                             DAA == "SOF/VEL" ~ VALUE/84))
```

```{r}
df_daa_dem_pts %>%
  group_by(CLASS_code, DAA) %>%
  summarise(SUM = sum(PTS_min)) 
```

```{r}
df_daa_dem_pts %>%
  summarise(SUM = sum(PTS_min)) 
```

```{r}
df_daa_dem_pts %>%
  distinct(DAA, SHEET, YEAR_str, .keep_all = TRUE) %>%
  summarise(sum = sum(PTS_max))
```


```{r}
df_daa_dem_pts %>%
  summarise(SUM = sum(PTS_max)) %>% 
  mutate(SUM_round = round(SUM))
```

```{r}
(306874.3 - 309969.8)/309969.8 * 100
```

# reorder age

```{r}
df_daa_dem_pts <- df_daa_dem_pts %>%
  mutate(AGE_ori = AGE) %>%
    mutate(AGE = fct_recode(AGE,
                          "0-19" = "0-4",
                          "0-19" = "5-9",
                          "0-19" = "10-14",
                          "0-19" = "15-19")) 
```

```{r}
levels_age <- df_daa_dem_pts %>%
  distinct(AGE, .keep_all = TRUE) %>%
  arrange(AGE) %>%
  pull(AGE)

levels_age 
```

```{r}
df_daa_dem_pts <- df_daa_dem_pts %>%
  mutate(AGE = factor(AGE, levels = levels_age))
```

```{r}
df_daa_dem_pts <- df_daa_dem_pts %>%
    mutate(SEX = if_else(SEX == "M", "Male", "Female")) %>%
  mutate(SEX = factor(SEX, levels = c("Male", "Female")))
```



```{r}
df_daa_dem_pts <- df_daa_dem_pts %>%
  mutate(YEAR_str = as.numeric(YEAR_str))
```

```{r}
df_daa_dem_pts %>%
  group_by(SEX, YEAR_str) %>%
  summarise(SUM = sum(PTS_max)) %>%
  pivot_wider(names_from = SEX,
              values_from = SUM) %>%
  mutate(EQ = Male > Female)
```


# sex difference
```{r}

p1_a1 <- df_daa_dem_pts %>%
  group_by(SEX, YEAR_str) %>%
  summarise(SUM = sum(PTS_max)) %>%
  ggplot(aes(YEAR_str, SUM, group = SEX, colour = SEX))+
  geom_line(linewidth = 0.3)+
  geom_point(size = 1) +
  scale_colour_manual(values = c("#1f77b4", "#d62728"))+
  scale_y_continuous(limits = c(0, 50000),
                     breaks = seq(0, 50000, 10000),
                     labels = label_comma())+
   coord_cartesian(clip = "off")+
  annotate(geom = "text",
           x = (2014+2023)/2,
           y = 50000,
           label = "Annual",
           size = 2.8,
           colour = "black",
           fontface = "bold")+
  labs(tag = "A",
       x = "Year",
       y = "Treated people (n)")+
  theme_classic()+
    theme(plot.tag = element_text(size = 12, colour = "black", face = "bold"),
        axis.title = element_text(size = 8, colour = "black", face = "bold"),
        axis.text.x = element_text(size = 8, colour = "black"),
        axis.text.y = element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"),
        legend.position = "none",
        legend.position.inside = c(1, 1),
        legend.justification = c(1, 1),
        legend.title = element_blank(),
        legend.text = element_text(size = 8, colour = "black"),
        plot.margin = margin(0,5,0,0, "mm"))

p1_a1 
```


```{r}
p1_a2 <- df_daa_dem_pts %>%
  group_by(SEX, YEAR_str) %>%
  summarise(SUM = sum(PTS_max)) %>%
  mutate(CUMSUM = cumsum(SUM)) %>%
  ggplot(aes(YEAR_str, CUMSUM, group = SEX, colour = SEX))+
  geom_line(linewidth = 0.3)+
  geom_point(size = 1) +
  geom_richtext(data = df_daa_dem_pts %>%
                  group_by(SEX, YEAR_str) %>%
                  summarise(SUM = sum(PTS_max)) %>%
                  mutate(CUMSUM = cumsum(SUM)) %>%
                  filter(YEAR_str == "2023") %>%
                  mutate(label = scales::comma(round(CUMSUM))) %>%
                  mutate(y = case_when(SEX == "Male" ~ CUMSUM - 200000/25,
                                       SEX == "Female" ~ CUMSUM + 200000/25)) %>%
                  mutate(vjust = case_when(SEX == "Male" ~ 1,
                                       SEX == "Female" ~ 0)),
                aes(x = YEAR_str, y = y, label = label, vjust = vjust),
                hjust = 0.5,
                size = 2.8,
                colour = "black",
                fill = NA, label.color = NA, 
                label.padding = grid::unit(rep(0, 4), "pt"),
                inherit.aes = NA)+
    annotate(geom = "text",
           x = (2014+2023)/2,
           y = 200000,
           label = "Cumulative",
           size = 2.8,
           colour = "black",
           fontface = "bold")+
  scale_colour_manual(values = c("#1f77b4", "#d62728"))+
  scale_y_continuous(limits = c(0, 200000),
                     breaks = seq(0, 200000, 50000),
                     labels = label_comma())+
   coord_cartesian(clip = "off")+
  
  labs(
       x = "Year",
       y = "Treated people (n)")+
  theme_classic()+
  theme(
        axis.title = element_text(size = 8, colour = "black", face = "bold"),
        axis.text.x = element_text(size = 8, colour = "black"),
        axis.text.y = element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"),
        legend.position = "inside",
        legend.position.inside = c(1, 0),
        legend.justification = c(1, 0),
       legend.background = element_blank(),
        legend.title = element_blank(),
        legend.text = element_text(size = 8, colour = "black"),
        plot.margin = margin(0,5,0,0, "mm"))

p1_a2
```

```{r}
p1_a <- p1_a1 + p1_a2+
  plot_layout(ncol = 2, widths = c(1, 1))

p1_a
```



#histogram

```{r}
df_daa_dem_pts <- df_daa_dem_pts %>%
  mutate(YEAR_str = as.character(YEAR_str))
```

```{r}
df_daa_dem_pts_n <- df_daa_dem_pts %>%
  group_by(AGE, SEX, YEAR_str) %>%
  summarise(SUM = sum(PTS_max)) 
```


```{r}
df_daa_dem_pts_n <- df_daa_dem_pts %>%
  group_by(AGE, YEAR_str) %>%
  summarise(SUM = sum(PTS_max)) %>%
  mutate(SEX = "Total") %>%
  bind_rows(df_daa_dem_pts_n) %>%
  mutate(SEX = factor(SEX, levels = c("Total", "Male", "Female")))
```

```{r}
df_daa_dem_pts_n %>%
  ungroup() %>%
  filter(SUM == max(SUM))
```


```{r}
df_daa_dem_pts_n %>%
  ggplot(aes(AGE, SUM, group = YEAR_str, colour = YEAR_str))+
  geom_line(linewidth = 0.3)+
  scale_colour_manual(values = as.vector(pals::kovesi.rainbow(n = 10)),
                      name = "Year")+
  scale_y_continuous(limits = c(0, 12000),
                     breaks = seq(0, 12000, 3000),
                     labels = label_comma())+
  facet_wrap2(vars(SEX),
              nrow = 1,
              axes = "all",
              remove_labels = "all")+
  labs(tag = "B",
       x = "Age",
       y = "Treated people (n)")+
  guides(colour = guide_legend(nrow = 2, byrow = TRUE,
                               title.position = "top",
                               override.aes = list(linewidth = 0.5)))+
  theme_classic()+
  theme(plot.tag = element_text(size = 12, colour = "black", face = "bold"),
        strip.background = element_blank(),
        strip.text.x = element_text(size = 8, colour = "black", face = "bold"),
        strip.text.y = element_blank(),
        axis.title = element_text(size = 8, colour = "black", face = "bold"),
        axis.text.x = element_text(size = 8, colour = "black",
                                   angle = 90, hjust = 1, vjust = 0.5),
        axis.text.y = element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"),
        legend.position = "bottom",
        legend.title = element_text(size = 8, colour = "black", face = "bold", hjust = 0.5),
        legend.text = element_text(size = 8, colour = "black"),
        panel.spacing.y = unit(5, "mm"),
        plot.margin = margin(0,0,0,0, "mm"))

```

```{r}
p1_b1 <- df_daa_dem_pts_n  %>%
  filter(SEX == "Total") %>%
  ggplot(aes(AGE, SUM, group = YEAR_str, colour = YEAR_str))+
  geom_line(linewidth = 0.3)+
  scale_colour_manual(values = as.vector(pals::kovesi.rainbow(n = 10)),
                      name = "Year")+
  scale_y_continuous(limits = c(0, 20000),
                     breaks = seq(0, 20000, 5000),
                     labels = label_comma())+
      annotate(geom = "text",
           x = (1+16)/2,
           y = 20000,
           label = "Total",
           size = 2.8,
           colour = "black",
           fontface = "bold")+
  labs(tag = "B",
       x = "Age",
       y = "Treated people (n)")+
  guides(colour = guide_legend(nrow = 2, byrow = TRUE,
                               title.position = "left",
                               override.aes = list(linewidth = 0.5)))+
  theme_classic()+
  theme(plot.tag = element_text(size = 12, colour = "black", face = "bold"),
        axis.title = element_text(size = 8, colour = "black", face = "bold"),
        axis.text.x = element_text(size = 8, colour = "black",
                                   angle = 90, hjust = 1, vjust = 0.5),
        axis.text.y = element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"),
        legend.position = "right",
        legend.background = element_blank(),
        legend.title = element_text(size = 8, colour = "black", face = "bold", hjust = 0.5),
        legend.text = element_text(size = 8, colour = "black"),
        plot.margin = margin(0,0,0,0, "mm"),
        legend.margin = margin(0, 0, 0, 0, "mm"))

p1_b1
```

```{r}
p1_bc_leg <- cowplot::get_legend(p1_b1)

 p1_bc_leg <- wrap_elements(p1_bc_leg)

 p1_bc_leg
```

```{r}
p1_b1 <- p1_b1 + theme(legend.position = "none")
```


```{r}
p1_b2 <- df_daa_dem_pts_n %>%
  filter(SEX == "Male") %>%
  ggplot(aes(AGE, SUM, group = YEAR_str, colour = YEAR_str))+
  geom_line(linewidth = 0.3)+
  scale_colour_manual(values = as.vector(pals::kovesi.rainbow(n = 10)),
                      name = "Year")+
  scale_y_continuous(limits = c(0, 12000),
                     breaks = seq(0, 12000, 3000),
                     labels = label_comma())+
  
        annotate(geom = "text",
           x = (1+16)/2,
           y = 12000,
           label = "Male",
           size = 2.8,
           colour = "black",
           fontface = "bold")+
  labs(
       x = "Age",
       y = "Treated people (n)")+
  guides(colour = guide_legend(nrow = 2, byrow = TRUE,
                               title.position = "top",
                               override.aes = list(linewidth = 0.5)))+
  theme_classic()+
  theme(
        axis.title = element_text(size = 8, colour = "black", face = "bold"),
        axis.text.x = element_text(size = 8, colour = "black",
                                   angle = 90, hjust = 1, vjust = 0.5),
        axis.text.y = element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"),
        legend.position = "none",
        legend.title = element_text(size = 8, colour = "black", face = "bold", hjust = 0.5),
        legend.text = element_text(size = 8, colour = "black"),
        plot.margin = margin(0,0,0,0, "mm"))

p1_b2
```

```{r}
p1_b3 <- df_daa_dem_pts_n %>%
  filter(SEX == "Female") %>%
  ggplot(aes(AGE, SUM, group = YEAR_str, colour = YEAR_str))+
  geom_line(linewidth = 0.3)+
  scale_colour_manual(values = as.vector(pals::kovesi.rainbow(n = 10)),
                      name = "Year")+
  scale_y_continuous(limits = c(0, 12000),
                     breaks = seq(0, 12000, 3000),
                     labels = label_comma())+
  
        annotate(geom = "text",
           x = (1+16)/2,
           y = 12000,
           label = "Female",
           size = 2.8,
           colour = "black",
           fontface = "bold")+
  labs(
       x = "Age",
       y = "Treated people (n)")+
  guides(colour = guide_legend(nrow = 2, byrow = TRUE,
                               title.position = "top",
                               override.aes = list(linewidth = 0.5)))+
  theme_classic()+
  theme(
        axis.title = element_text(size = 8, colour = "black", face = "bold"),
        axis.text.x = element_text(size = 8, colour = "black",
                                   angle = 90, hjust = 1, vjust = 0.5),
        axis.text.y = element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"),
        legend.position = "none",
        legend.title = element_text(size = 8, colour = "black", face = "bold", hjust = 0.5),
        legend.text = element_text(size = 8, colour = "black"),
        plot.margin = margin(0,0,0,0, "mm"))

p1_b3
```


```{r}
df_daa_dem_pts_pct <- df_daa_dem_pts_n %>%
  group_by(SEX, YEAR_str) %>%
  mutate(ALL = sum(SUM)) %>%
  mutate(PCT = SUM/ALL * 100)
```



```{r}
p1_c1 <- df_daa_dem_pts_pct %>%
  filter(SEX =="Total") %>%
  ggplot(aes(AGE, PCT, group = YEAR_str, colour = YEAR_str))+
  geom_line(linewidth = 0.3)+
  scale_colour_manual(values = as.vector(pals::kovesi.rainbow(n = 10)),
                      name = "Year")+
    scale_y_continuous(limits = c(0, 30),
                     breaks = seq(0, 30, 10),
                     labels = label_comma())+
        annotate(geom = "text",
           x = (1+16)/2,
           y = 30,
           label = "Total",
           size = 2.8,
           colour = "black",
           fontface = "bold")+
  labs(
       tag  = "C",
       x = "Age", y = "Proportion (%)")+
  guides(colour = guide_legend(nrow = 2, byrow = TRUE,
                               title.position = "top",
                               override.aes = list(linewidth = 0.5)))+
  theme_classic()+
  theme(plot.tag = element_text(size = 12, colour = "black", face = "bold"),
        axis.title = element_text(size = 8, colour = "black", face = "bold"),
        axis.text.x = element_text(size = 8, colour = "black",
                                   angle = 90, hjust = 1, vjust = 0.5),
        axis.text.y = element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"),
        legend.position = "none",
        legend.title = element_text(size = 8, colour = "black", face = "bold", hjust = 0.5),
        legend.text = element_text(size = 8, colour = "black"),
        plot.margin = margin(0,0,0,0, "mm"))

p1_c1
```

```{r}
p1_c2 <- df_daa_dem_pts_pct %>%
  filter(SEX =="Male") %>%
  ggplot(aes(AGE, PCT, group = YEAR_str, colour = YEAR_str))+
  geom_line(linewidth = 0.3)+
  scale_colour_manual(values = as.vector(pals::kovesi.rainbow(n = 10)),
                      name = "Year")+
    scale_y_continuous(limits = c(0, 30),
                     breaks = seq(0, 30, 10),
                     labels = label_comma())+
        annotate(geom = "text",
           x = (1+16)/2,
           y = 30,
           label = "Male",
           size = 2.8,
           colour = "black",
           fontface = "bold")+
  
  labs(
       x = "Age",
       y = "Proportion (%)")+
  guides(colour = guide_legend(nrow = 2, byrow = TRUE,
                               title.position = "top",
                               override.aes = list(linewidth = 0.5)))+
  theme_classic()+
  theme(
        plot.title = element_text(size = 8, colour = "black", face = "bold", hjust = 0.5),
        axis.title = element_text(size = 8, colour = "black", face = "bold"),
        axis.text.x = element_text(size = 8, colour = "black",
                                   angle = 90, hjust = 1, vjust = 0.5),
        axis.text.y = element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"),
        legend.position = "none",
        legend.title = element_text(size = 8, colour = "black", face = "bold", hjust = 0.5),
        legend.text = element_text(size = 8, colour = "black"),
        plot.margin = margin(0,0,0,0, "mm"))

p1_c2
```

```{r}
p1_c3 <- df_daa_dem_pts_pct %>%
  filter(SEX =="Female") %>%
  ggplot(aes(AGE, PCT, group = YEAR_str, colour = YEAR_str))+
  geom_line(linewidth = 0.3)+
  scale_colour_manual(values = as.vector(pals::kovesi.rainbow(n = 10)),
                      name = "Year")+
    scale_y_continuous(limits = c(0, 30),
                     breaks = seq(0, 30, 10),
                     labels = label_comma())+
        annotate(geom = "text",
           x = (1+16)/2,
           y = 30,
           label = "Female",
           size = 2.8,
           colour = "black",
           fontface = "bold")+
  
  labs(
       x = "Age",
       y = "Proportion (%)")+
  guides(colour = guide_legend(nrow = 2, byrow = TRUE,
                               title.position = "top",
                               override.aes = list(linewidth = 0.5)))+
  theme_classic()+
  theme(
        plot.title = element_text(size = 8, colour = "black", face = "bold", hjust = 0.5),
        axis.title = element_text(size = 8, colour = "black", face = "bold"),
        axis.text.x = element_text(size = 8, colour = "black",
                                   angle = 90, hjust = 1, vjust = 0.5),
        axis.text.y = element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"),
        legend.position = "none",
        legend.title = element_text(size = 8, colour = "black", face = "bold", hjust = 0.5),
        legend.text = element_text(size = 8, colour = "black"),
        plot.margin = margin(0,0,0,0, "mm"))

p1_c3
```


```{r}
#p2_b1 <- p2_b1 + theme(axis.title.x = element_blank())

p1_b2 <- p1_b2 + theme(axis.title.y = element_blank())

p1_b3 <- p1_b3 + theme(#axis.title.x = element_blank(),
                       axis.title.y =  element_blank())
```

```{r}
#p2_c1 <- p2_c1 + theme(axis.title.x = element_blank())

p1_c2 <- p1_c2 + theme(axis.title.y = element_blank())

p1_c3 <- p1_c3 + theme(#axis.title.x = element_blank(),
                       axis.title.y =  element_blank())
```

```{r}
p1_a <- patchwork::free(p1_a1, side = "l", type = "label") + 
  patchwork::free(p1_a2, side = "l", type = "label") + 
  plot_layout(nrow = 1, ncol = 2)

p1_bc <- patchwork::free(p1_b1, side = "l", type = "label")+ p1_b2 + p1_b3 + 
  patchwork::free(p1_c1, side = "l", type = "label")+ p1_c2 + p1_c3 + 
  plot_layout(nrow = 2, ncol = 3)
```


```{r}
p1 <- p1_a + 
  p1_bc +
  p1_bc_leg +
  plot_layout(design = "
              AAABBB
              AAABBB
              AAABBB
              AAABBB
              CCCCCC
              CCCCCC
              CCCCCC
              CCCCCC
              CCCCCC
              CCCCCC
              CCCCCC
              CCCCCC
              DDDDDD")

```


```{r}
ggsave( "../figure/Fig4.pdf", plot = p1,  height = 235, width = 180, units = "mm",
        device = cairo_pdf)
```

```{r}
saveRDS(df_daa_dem_pts, "../df/daa/analysis/df_daa_dem_pts")
```

