---
title: "HCV DAA"
output: html_document
date: "2025-11-20"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readxl)
library(openxlsx)

library(sf)
library(scales)

library(ggtext)
library(ggrepel)

library(broom)
library(glue)

library(patchwork)
library(mapdata)
```

```{r}
# make df SHEET

dir.create("../plot", showWarnings = TRUE, recursive = FALSE, mode = "0777")
```

```{r}
daa_file <- list.files("../df/filter") 
daa_file
```

```{r}
#df_daa_dem_total <- readRDS("../df/filter/df_daa_dem_total")
```


```{r}
df_daa_prf_agg <- readRDS("../df/daa/analysis/df_daa_prf_agg")
```

```{r}
df_daa_dem_pts <- readRDS("../df/daa/analysis/df_daa_dem_pts")
```

```{r}
df_pop_prf <- readRDS("../rds/pop/prf/df_pop_prf")
```



```{r}
df_daa_prf %>% filter(is.na(VALUE)) %>% View()
```


# df_dem_daa


```{r}
# remove dcv ebr
df_daa_prf_pts <- df_daa_prf_agg %>%
  filter(!DAA_ind %in% c("DCV", "EBR"))
```

```{r}
# calculate min pts by dividing by max duration

df_daa_prf_pts <- df_daa_prf_pts %>%
  mutate(PTS_min = case_when(DAA == "DCV/ASV" ~ VALUE/(168*2),
                             DAA == "EBR/GZR" ~ VALUE/(84*2),
                             DAA %in% c(
                                        "OBV/PTV/r",
                                        "SOF",
                                        "SOF/LDV") ~ VALUE/84,
                             DAA == "GLE/PIB" ~ VALUE/(84*3),
                             DAA == "SOF/VEL" ~ VALUE/168))

```

```{r}
# calculate mx pts by dividing min duration

df_daa_prf_pts <- df_daa_prf_pts %>%
  mutate(PTS_max = case_when(DAA == "DCV/ASV" ~ VALUE/(168*2),
                             DAA == "EBR/GZR" ~ VALUE/(84*2),
                             DAA %in% c(
                                        "OBV/PTV/r",
                                        "SOF",
                                        "SOF/LDV") ~ VALUE/84,
                             DAA == "GLE/PIB" ~ VALUE/(56*3),
                             DAA == "SOF/VEL" ~ VALUE/84))
```

```{r}
df_daa_prf_pts %>% summarise(SUM = sum(PTS_max)) #%>%
#  mutate(SUM_round = round(SUM))
```

```{r}
(301070	- 309969.8	)/309969.8	 * 100
```

```{r}
(291280	- 299796)/299796 * 100
```


```{r}
df_daa_prf_pts %>% count(DAA)
```


```{r}
df_daa_prf_pts %>% count(SHEET)
```


```{r}
df_daa_prf_pts %>% 
  distinct(DAA, YEAR_str, SHEET, .keep_all = TRUE) %>%
  count(DAA, YEAR_str)
```

```{r}
df_daa_prf_total <- df_daa_prf_pts %>%
  distinct(DAA, YEAR_str, SHEET, .keep_all = TRUE) %>%
   mutate(PTS_max = case_when(DAA == "DCV/ASV" ~ TOTAL/(168*2),
                              DAA == "EBR/GZR" ~ TOTAL/(84*2),
                             DAA %in% c(
                                        "OBV/PTV/r",
                                        "SOF",
                                        "SOF/LDV") ~ TOTAL/84,
                             DAA == "GLE/PIB" ~ TOTAL/(56*3),
                             DAA == "SOF/VEL" ~ TOTAL/84)) %>%
  group_by(YEAR_str) %>%
  summarise(SUM_total = sum(PTS_max))

df_daa_prf_total 
```

```{r}
df_daa_prf_total %>%
  summarise(SUM = sum(SUM_total))
```


```{r}
df_daa_prf_value <- df_daa_prf_pts %>%
  group_by(YEAR_str) %>%
  summarise(SUM_value = sum(PTS_max)) 


df_daa_prf_value 
```

```{r}
df_daa_prf_diff <- df_daa_prf_total %>%
  left_join(df_daa_prf_value,
            by = join_by(YEAR_str))
```


# DCV/ASV

```{r}
df_daa_prf_pts %>%
  filter(DAA == "DCV/ASV") %>%
  group_by(PRF, YEAR_str) %>%
  summarise(SUM = sum(PTS_max)) %>%
  ggplot(aes(PRF, SUM))+
  geom_col()+
  facet_grid(rows = vars(YEAR_str), scales = "free_y")+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5))
```

```{r}
df_daa_prf_pts %>%
  filter(DAA == "SOF") %>%
  group_by(PRF, YEAR_str) %>%
  summarise(SUM = sum(PTS_max)) %>%
  ggplot(aes(PRF, SUM))+
  geom_col()+
  facet_grid(rows = vars(YEAR_str), scales = "free_y")+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5))
```

```{r}
df_daa_prf_pts %>%
  filter(DAA == "SOF/LDV") %>%
  group_by(PRF, YEAR_str) %>%
  summarise(SUM = sum(PTS_max)) %>%
  ggplot(aes(PRF, SUM))+
  geom_col()+
  facet_grid(rows = vars(YEAR_str), scales = "free_y")+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5))
```

```{r}
df_daa_prf_pts %>%
  filter(DAA == "GLE/PIB") %>%
  group_by(PRF, YEAR_str) %>%
  summarise(SUM = sum(PTS_max)) %>%
  ggplot(aes(PRF, SUM))+
  geom_col()+
  facet_grid(rows = vars(YEAR_str), scales = "free_y")+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5))
```

# total number of people treated


```{r}
# whole year

df_daa_prf_pts %>%
  group_by(PRF) %>%
  summarise(SUM = sum(PTS_max)) %>%
  ggplot(aes(PRF, SUM))+
  geom_col()+
  scale_y_continuous(expand = c(0, 0),
                     breaks = seq(0, 30000, 10000),
                     limits = c(0, 30000))+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5))
```

```{r}
# facet by year

df_daa_prf_pts %>%
  group_by(PRF, YEAR_str) %>%
  summarise(SUM = sum(PTS_max)) %>%
  ggplot(aes(PRF, SUM))+
  geom_col()+
  facet_grid(rows = vars(YEAR_str), scales = "free_y") +
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5))
```

```{r}
df_daa_prf_pts %>%
  group_by(PRF, YEAR_str) %>%
  summarise(SUM = sum(PTS_max)) %>%
  ggplot(aes(YEAR_str, SUM))+
  geom_point()+
  facet_wrap(vars(PRF), scales = "free_y") +
  theme_classic()+
  theme(strip.background =element_blank(),
        axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5))
```



# japan map

```{r}
map_japan <- maps::map("japan", 
                       plot = FALSE,
                       fill = TRUE) %>%
  st_as_sf() %>%
  rename(PRF = "ID") %>%
  mutate(PRF = str_to_title(PRF)) 
```


```{r}
map_japan <- map_japan %>%
  left_join(df_daa_prf_pts %>%
              group_by(PRF) %>%
              summarise(SUM = sum(PTS_max)),
            by = join_by(PRF))
```

```{r}
map_japan %>% as_tibble() %>%summarise(
                        MIN = min(SUM))
```


```{r}
map_japan %>%
  ggplot() +
  geom_sf(aes(fill = SUM)) +
  scale_fill_gradient(low= "#FFFFCC", high = "#E31A1C", na.value = "#d9d9d9",
                      limits = c(0, 30000)) +
  scale_x_continuous(limits = c(122.5, 147))+
  theme_void()
```

```{r}
map_japan %>%
  ggplot() +
  geom_sf(aes(fill = SUM)) +

  scale_fill_gradient(low= "#ffffcc", high = "#e31a1c", na.value = "#d9d9d9",
                      limits = c(0, 30000)) +
  labs(tag = "",
       fill = "Number of\ntreated people")+
  guides(fill = guide_colourbar(ticks.colour = "black",
                                ticks.linewidth = 0.2,
                                frame.colour = "black",
                                frame.linewidth = 0.2)) +
  scale_x_continuous(limits = c(122.5, 147.5))+
  theme_void()
```


# region

```{r}
df_daa_prf_pts %>%
  group_by(PRF, iso_3166_2) %>% count()
```

```{r}
hokkaido <- c("JP-01")

tohoku <- c(paste0("JP-0", as.character(2:7)))

kanto <- c(paste0("JP-0", as.character(8:9)), 
           paste0("JP-", as.character(10:14)))

chubu <- c(paste0("JP-", as.character(15:24)))

kinki <- c(paste0("JP-", as.character(25:30)))

chugoku <- c(paste0("JP-", as.character(31:35)))

shikoku <- c(paste0("JP-", as.character(36:39)))

kyushu_okinawa <- c(paste0("JP-", as.character(40:47)))

```


```{r}
factor_reg <- c("Hokkaido",
                "Tohoku",
                "Kanto",
                "Chubu",
                "Kansai",
                "Chugoku",
                "Shikoku",
                "Kyushu\nOkinawa")
```


```{r}
df_daa_prf_pts <- df_daa_prf_pts %>%
  mutate(REG = case_when(iso_3166_2 %in% hokkaido ~ "Hokkaido",
                         iso_3166_2 %in% tohoku ~ "Tohoku",
                         iso_3166_2 %in% kanto ~ "Kanto",
                         iso_3166_2 %in% chubu ~ "Chubu",
                         iso_3166_2 %in% kinki ~ "Kansai",
                         iso_3166_2 %in% chugoku ~ "Chugoku",
                         iso_3166_2 %in% shikoku ~ "Shikoku",
                         iso_3166_2 %in% kyushu_okinawa ~ "Kyushu\nOkinawa")) %>%
  mutate(REG = factor(REG, levels = factor_reg))
```


```{r}
p1_c1 <- df_daa_prf_pts %>%
  group_by(REG) %>%
  summarise(SUM = sum(PTS_max)) %>%
  ggplot(aes(REG, SUM, fill = REG))+
  geom_col(width = 0.7)+
      scale_fill_manual(values = c("#1f77b4",
                               "#bcbd22",
                               "#e377c2",
                               "#7f7f7f",
                               "#ff7f0e",
                               "#2ca02c",
                               "#9467bd",
                               "#d62728"))+
  scale_y_continuous(expand = c(0, 0),
                     breaks = seq(0, 100000, 25000),
                     limits = c(0, 100000),
                     labels = label_comma())+
    labs(tag = "C",
         x= "Region",
         y = "Treated people\n(n)")+
  theme_classic()+
  theme(plot.tag = element_text(size = 12, colour = "black", face = "bold"),
        axis.title.x = element_blank(),
        axis.title.y = element_text(size = 8, colour = "black", face = "bold"),
        axis.text.x = element_blank(),
        axis.text.y = element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"),
        legend.position = "none",
        legend.title = element_text(size = 8, colour = "black", face = "bold"),
        legend.text = element_text(size = 8, colour = "black"),
        panel.background = element_blank(),
        plot.margin = margin(0, 0, 0, 0, unit = "mm"))

p1_c1
```

```{r}
# world map by region
p1_d2 <- map_japan %>%
    left_join(df_daa_prf_pts %>% distinct(PRF, REG),
            by = join_by(PRF)) %>%
  ggplot()+
  geom_sf(aes(fill = REG), alpha = 0.7,
          linewidth = 0.2)+
  scale_fill_manual(values = c("#1f77b4",
                               "#bcbd22",
                               "#e377c2",
                               "#7f7f7f",
                               "#ff7f0e",
                               "#2ca02c",
                               "#9467bd",
                               "#d62728"),
                    name = "Region"
                               )+
  scale_x_continuous(limits = c(124, 148))+
  scale_y_continuous(limits = c(25, 45)) +
  guides(fill = guide_legend(override.aes = list(alpha = 1, size = 2.8, colour = NA))) +
  theme_void()+
  theme(legend.title = element_text(size = 8, colour = "black", face = "bold"),
        legend.text = element_text(size = 8, colour = "black"),
        legend.position = "none",
        plot.margin = margin(c(0, 0, 0, 0), unit = "mm"))

p1_d2
```

```{r}
saveRDS(p1_d2,  "../plot/p_jp_reg")
```

```{r}
df_daa_prf_pts %>%
  group_by(REG, YEAR_str) %>%
  summarise(SUM = sum(PTS_max)) %>%
  ggplot(aes(REG, SUM))+
  geom_col()+
  facet_wrap(vars(YEAR_str), scales = "free")+
  theme_classic()+
  theme(strip.background = element_blank(),
        strip.text = element_text(size = 8, colour = "black", face = "bold"),
        axis.text.x = element_text(size = 8, colour = "black", angle = 90, hjust =1, vjust = 0.5))
```

```{r}
# whole year

p_prf_total <- df_daa_prf_pts %>%
  group_by(PRF, iso_3166_2) %>%
  summarise(SUM = sum(PTS_max)) %>%
  left_join(df_daa_prf_pts %>% distinct(iso_3166_2, REG),
            by = join_by(iso_3166_2)) %>%
  ggplot(aes(fct_reorder(PRF, iso_3166_2), SUM, fill = REG))+
  geom_col(width = 0.7, alpha = 1)+
    scale_fill_manual(values = c("#1f77b4",
                               "#bcbd22",
                               "#e377c2",
                               "#7f7f7f",
                               "#ff7f0e",
                               "#2ca02c",
                               "#9467bd",
                               "#d62728"),
                      name = "Region")+
  scale_y_continuous(expand = c(0, 0),
                     breaks = seq(0, 30000, 10000),
                     limits = c(0, 30000),
                      labels = label_comma())+
  labs(x= "Prefecture", y = "Treated people\n(total)")+
  theme_classic()+
  theme(axis.title = element_text(size = 8, colour = "black", face = "bold"),
        axis.text.x = element_text(size = 8, colour = "black", angle = 90, hjust = 1, vjust = 0.5),
        axis.text.y = element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"),
        legend.position = "none",
        legend.title = element_text(size = 8, colour = "black", face = "bold"),
        legend.text = element_text(size = 8, colour = "black"),
        plot.margin = margin(0, 0, 0, 0, unit = "mm"))

p_prf_total
```

```{r}
df_pop_prf_2015 <- df_pop_prf %>%
  filter(YEAR == "2015" & PRF_jp != "total") %>%
  rename(ALL_2015 = "ALL_total") %>%
  select(PRF_jp, ALL_2015)
```

```{r}
df_pop_prf_adj <- df_pop_prf %>%
  left_join(df_pop_prf_2015,
            by = join_by(PRF_jp)) %>%
  mutate(ID = paste0(YEAR, "_", PRF_jp))
```

```{r}
df_daa_prf_pts_adj <- df_daa_prf_pts %>%
  distinct(FILE, SHEET, DAA, PRF, PRF_jp, iso_3166_2, .keep_all = TRUE) %>%
  ungroup() %>%
  group_by(YEAR_str, PRF, PRF_jp, iso_3166_2) %>%
  summarise(SUM = sum(PTS_max)) %>%
  ungroup()

df_daa_prf_pts_adj
```

```{r}
df_daa_prf_pts_adj %>% summarise(n = sum(SUM))
```


```{r}
df_daa_prf_pts_adj <- df_daa_prf_pts_adj %>%
  mutate(ID = paste0(YEAR_str, "_", PRF_jp)) %>%
  left_join(df_pop_prf_adj %>% select(!PRF_jp),
            by = join_by(ID))

df_daa_prf_pts_adj 
```


```{r}
df_daa_prf_pts_adj <- df_daa_prf_pts_adj %>%
  mutate(SUM_2015 = SUM * ALL_2015/ALL_total) %>%
  group_by(PRF_jp,PRF,  iso_3166_2) %>%
  summarise(SUM_adj = sum(SUM_2015)) %>%
  left_join(df_pop_prf_2015,
            by = join_by(PRF_jp)) 

df_daa_prf_pts_adj
```

```{r}
df_daa_prf_pts_adj <- df_daa_prf_pts_adj %>%
  left_join(df_daa_prf_pts %>% distinct(iso_3166_2, REG),
            by = join_by(iso_3166_2))
```


```{r}
p1_a1 <- df_daa_prf_pts_adj %>%
  ggplot(aes(fct_reorder(PRF, iso_3166_2), SUM_adj, fill = REG))+
  geom_col(width = 0.7, alpha = 1)+
    scale_fill_manual(values = c("#1f77b4",
                               "#bcbd22",
                               "#e377c2",
                               "#7f7f7f",
                               "#ff7f0e",
                               "#2ca02c",
                               "#9467bd",
                               "#d62728"),
                      name = "Region")+
  scale_y_continuous(expand = c(0, 0),
                     breaks = seq(0, 30000, 10000),
                     limits = c(0, 30000),
                      labels = label_comma())+
  labs(tag = "A",
       x= "Prefecture", y = "Treated people\n(n)")+
  theme_classic()+
  theme(plot.tag = element_text(size = 12, colour = "black", face = "bold"),
        axis.title.x = element_blank(),
    axis.title.y = element_text(size = 8, colour = "black", face = "bold"),
        axis.text.x = element_blank(),
        axis.text.y = element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"),
        legend.position = "none",
        legend.title = element_text(size = 8, colour = "black", face = "bold"),
        legend.text = element_text(size = 8, colour = "black"),
    plot.margin = margin(0, 0, 0, 0, unit = "mm"))

p1_a1
```

```{r}
df_daa_prf_pts_adj <- df_daa_prf_pts_adj %>%
  mutate(PCT = SUM_adj/ (ALL_2015 * 1000) *100 )
```

```{r}
df_daa_prf_pts_adj %>%
  ggplot(aes(PCT))+
  geom_histogram(binwidth = 0.02)
```



```{r}
df_daa_prf_pts_adj %>%
  ungroup() %>%
  summarise(AVR = sum(SUM_adj) / (sum(ALL_2015) *1000 ) *100)
```

```{r}
pct_mean <- df_daa_prf_pts_adj %>%
  ungroup() %>%
  summarise(MEAN = sum(SUM_adj) / (sum(ALL_2015) *1000 ) *100) %>%
  pull(MEAN) 

pct_mean
```




```{r}
p1_a2 <- df_daa_prf_pts_adj %>%
  ggplot(aes(fct_reorder(PRF, iso_3166_2), PCT, fill = REG))+
  geom_col(width = 0.7, alpha = 1)+
  geom_hline(yintercept = pct_mean, linewidth = 0.3, linetype = 2)+
    scale_fill_manual(values = c("#1f77b4",
                               "#bcbd22",
                               "#e377c2",
                               "#7f7f7f",
                               "#ff7f0e",
                               "#2ca02c",
                               "#9467bd",
                               "#d62728"),
                      name = "Region")+
  scale_y_continuous(expand = c(0, 0),
                     breaks = c(seq(0, 0.5, 0.1)),
                     limits = c(0, 0.5),
                      labels = label_comma())+
  labs(x= "Prefecture", y = "Prevalence\n(%)")+
  theme_classic()+
  theme(axis.title = element_text(size = 8, colour = "black", face = "bold"),
        axis.text.x = element_text(size = 8, colour = "black", angle = 90, hjust = 1, vjust = 0.5),
        axis.text.y = element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"),
        legend.position = "none",
        legend.title = element_text(size = 8, colour = "black", face = "bold"),
        legend.text = element_text(size = 8, colour = "black"),
        plot.margin = margin(0, 0, 0, 0, unit = "mm"))

p1_a2
```

```{r}
p1_a <- p1_a1 +
  plot_spacer() +
  p1_a2 +
  plot_layout(nrow = 3, heights = c(1, 0.05, 1))

p1_a
```


```{r}
p1_b1 <- map_japan %>%
  ggplot() +
  geom_sf(aes(fill = SUM),
          linewidth = 0.2) +
 scale_fill_gradient(low= "white", high = "#E64626", na.value = "#d9d9d9",
                      limits = c(0, 30000),
                     labels = label_comma()) +
  labs(fill = "Treated people\n(n)")+
  guides(fill = guide_colourbar(ticks.colour = "black",
                                ticks.linewidth = 0.2,
                                frame.colour = "black",
                                frame.linewidth = 0.2)) +
  scale_x_continuous(limits = c(124, 148))+
  scale_y_continuous(limits = c(25, 45)) +
  labs(tag = "B")+
  theme_void()+
  theme(plot.tag =element_text(size = 12, colour = "black", face = "bold"),
        legend.title = element_text(size = 8, colour = "black", face = "bold"),
        legend.text = element_text(size = 8, colour = "black"),
        legend.position = "inside",
        legend.justification = c(0, 0.5),
        legend.justification.inside = c(1.2, 0.5),
        legend.background = element_blank(),
          legend.key.width  = unit(0.75, "lines"),
        legend.key.height = unit(1.5, "lines"),
        panel.background = element_blank(),
        plot.margin = margin(0, 0, 0, 0, "mm"))

p1_b1
```



```{r}
##8c564b
# #bd0026 red
p1_b2 <- map_japan %>%
  left_join(df_daa_prf_pts_adj,
            by = join_by(PRF)) %>%
  ggplot() +
  geom_sf(aes(fill = PCT),
          linewidth = 0.2) +
 scale_fill_gradient(low= "white", high = "#E64626", na.value = "#d9d9d9",
                      limits = c(0.0, 0.5),
                     labels = label_comma()) +
  labs(fill = "Prevalence\n(%)")+
  guides(fill = guide_colourbar(ticks.colour = "black",
                                ticks.linewidth = 0.2,
                                frame.colour = "black",
                                frame.linewidth = 0.2)) +
  scale_x_continuous(limits = c(124, 148))+
  scale_y_continuous(limits = c(25, 45)) +
  theme_void()+
 theme(plot.tag =element_text(size = 12, colour = "black", face = "bold"),
        legend.title = element_text(size = 8, colour = "black", face = "bold"),
        legend.text = element_text(size = 8, colour = "black"),
        legend.position = "inside",
        legend.justification = c(0, 0.5),
        legend.justification.inside = c(1.1, 0.5),
        legend.background = element_blank(),
          legend.key.width  = unit(0.75, "lines"),
        legend.key.height = unit(1.5, "lines"),
        panel.background = element_blank(),
        plot.margin = margin(0, 0, 0, 0, "mm"))

p1_b2
```

```{r}
# region percentage

p1_c2 <- df_daa_prf_pts_adj %>%
  group_by(REG) %>%
  summarise(SUM_reg = sum(SUM_adj),
            ALL_reg = sum(ALL_2015)) %>%
  mutate(PCT = SUM_reg/(ALL_reg * 1000)*100) %>%
  ggplot(aes(REG, PCT, fill = REG))+
  geom_col(width = 0.7)+
  geom_hline(yintercept = pct_mean, linewidth = 0.3, linetype = 2)+
 scale_fill_manual(values = c("#1f77b4",
                               "#bcbd22",
                               "#e377c2",
                               "#7f7f7f",
                               "#ff7f0e",
                               "#2ca02c",
                               "#9467bd",
                               "#d62728"))+
  scale_y_continuous(expand = c(0, 0),
                     breaks = seq(0, 0.4, 0.1),
                     limits = c(0, 0.4),
                     labels = label_comma())+
    labs(x= "Region",
         y = "Prevalence\n(%)")+
  theme_classic()+
  theme(plot.tag = element_text(size = 12, colour = "black", face = "bold"),
        axis.title = element_text(size = 8, colour = "black", face = "bold"),
        axis.text.x = element_text(size = 8, colour = "black", angle = 90, hjust = 1, vjust = 0.5),
        axis.text.y = element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"),
        legend.position = "none",
        legend.title = element_text(size = 8, colour = "black", face = "bold"),
        legend.text = element_text(size = 8, colour = "black"),
        panel.background = element_blank(),
        plot.margin = margin(0, 0, 0, 0, unit = "mm"))

p1_c2 
```

```{r}
p1_c <-  p1_c1+ 
  plot_spacer() + 
  p1_c2 +
  plot_layout(nrow = 3, heights = c(1, 0.05, 1))

p1_c
```


```{r}
df_prf_reg_all <-   df_daa_prf_pts_adj %>%
  ungroup() %>%
  mutate(ALL_2015 =ALL_2015/1000) %>%
  select(SUM_adj, ALL_2015) %>%
  nest() %>%
  mutate(
    fit = purrr::map(data, ~ lm(SUM_adj ~ ALL_2015, data = .x)),
    tidied = purrr::map(fit, tidy),
    glanced = purrr::map(fit, glance),
    augmented = purrr::map(fit, augment)
  )
```

```{r}
# tidy
df_prf_reg_all_tidy <- df_prf_reg_all %>% unnest(tidied)

df_prf_reg_all_tidy
```

```{r}
df_prf_reg_all_tidy %>% select(term, estimate) %>% 
  mutate(term = str_remove_all(term, "\\(|\\)")) %>%
              pivot_wider(names_from = term, values_from = estimate) 
```


```{r}
df_prf_reg_all %>% unnest(glanced)
```

```{r}
df_reg_all_label <- df_prf_reg_all %>% unnest(glanced) %>%
  mutate(term = "ALL_2015") %>%
  left_join(df_prf_reg_all_tidy %>% select(term, estimate) %>% mutate(term = str_remove_all(term, "\\(|\\)")) %>%
              pivot_wider(names_from = term, values_from = estimate) %>%
              mutate(term = "ALL_2015"),
            by = join_by(term)) %>%
  mutate(label = glue("*y* = {round(ALL_2015, 0)}*x* + {round(Intercept, 0)}<br>*p* < 0.001<br>*R*<sup>2</sup><sub>adj</sub> = {round(adj.r.squared, 2)}")) 
```



```{r}

p1_d1 <- df_daa_prf_pts_adj %>%
   mutate(ALL_2015 = ALL_2015/1000) %>%
  ggplot(aes(ALL_2015, SUM_adj))+
   geom_point( aes(fill = REG), colour = "black", alpha = 0.7, shape = 21,
               size = 1.5)+
   scale_fill_manual(values = c("#1f77b4",
                               "#bcbd22",
                               "#e377c2",
                               "#7f7f7f",
                               "#ff7f0e",
                               "#2ca02c",
                               "#9467bd",
                               "#d62728"),
                      name = "Region")+
 # scale_size_continuous(range = c(1.5, 4))+
  geom_richtext(data = df_reg_all_label,
                aes(x = 0, y = 30000, label = label),
                size = 2.8,
                hjust = 0, vjust = 1,
                fill = NA, label.color = NA)+
    geom_line(stat="smooth",
              method = "lm", 
              size = 0.5,
              linetype = 1,
              alpha = 0.7,
              colour = "#17becf")+
    geom_text_repel(data = df_daa_prf_pts_adj %>%
                      mutate(ALL_2015 = ALL_2015/1000) %>%
                      filter(PRF %in% c("Hokkaido",
                                      #  "Aomori",
                                        "Miyagi",
                                      #  "Ibaraki",
                                      #  "Tochigi",
                                      #  "Gunma",
                                        "Saitama",
                                        "Chiba",
                                        "Tokyo",
                                        "Kanagawa",
                                      #  "Yamanashi",
                                        "Shizuoka",
                                        "Aichi",
                                      #  "Kyoto",
                                        "Osaka",
                                        "Hyogo",
                                      #  "Wakayama",
                                      #  "Tottori",
                                      #  "Okayama",
                                        "Hiroshima",
                                     #   "Ehime",
                                        "Fukuoka",
                                      #  "Saga",
                                     #   "Kumamoto",
                                        "Okinawa")),
                    aes(x = ALL_2015, 
                        y = SUM_adj,
                        label = PRF),
                  size = 2.6, 
                  segment.size = 0.3, segment.alpha = 0.5,
                  max.overlaps = Inf,
                  seed = 56,
                  inherit.aes = FALSE)+
  scale_x_continuous(breaks = seq(0, 15, 5),
                     limits = c(0, 15))+
  scale_y_continuous(breaks = seq(0, 30000, 10000),
                     limits = c(0, 30000),
                     labels = label_comma())+
  labs(tag = "D",
       x = "Prefecture population (10<sup>6</sup>)",
       y = "Treated people (n)")+
  theme_classic()+
  theme(plot.tag = element_text(size = 12, colour = "black", face = "bold"),
        axis.title.x = element_markdown(size = 8, colour = "black", face = "bold"),
        axis.title.y = element_text(size = 8, colour = "black", face = "bold"),
        axis.text = element_text(size = 8, colour = "black"),
        axis.line = element_line(linewidth = 0.3, colour = "black"),
        axis.ticks = element_line(linewidth = 0.3, colour = "black"),
        legend.position = "none",
        panel.background = element_blank())

p1_d1
```


```{r}
p1_d <- p1_d1 +
  inset_element(p1_d2, 0.4, 0, 1, 0.8)

p1_d
```


```{r}
p1 <- patchwork::free(p1_a, side = "tblr") + 
  patchwork::free(p1_b1, side = "l") + 
  patchwork::free(p1_b2, side = "lr") + 
  patchwork::free(p1_c, side = "trbl") +
  patchwork::free(p1_d, side = "trbl") +
  plot_layout(design = "
              AAAAAAAAAAAAAA
              AAAAAAAAAAAAAA
              AAAAAAAAAAAAAA
              BBBBBBBCCCCCCC
              BBBBBBBCCCCCCC
              BBBBBBBCCCCCCC
              DDDDDDEEEEEEEE
              DDDDDDEEEEEEEE
              DDDDDDEEEEEEEE") 

p1
```


```{r}
ggsave("../figure/Fig5.pdf", p1, height = 235, width = 180,  units ="mm")

```

