---
title: "HCV DAA"
output: html_document
date: "2025-11-30"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(rvest)
```

```{r}
# create directories

dir.create("../xlsx/cost", showWarnings = TRUE, recursive = FALSE, mode = "0777")


dir.create("../xlsx/cost/all", showWarnings = TRUE, recursive = FALSE, mode = "0777")
dir.create("../xlsx/cost/dem", showWarnings = TRUE, recursive = FALSE, mode = "0777")
dir.create("../xlsx/cost/sa", showWarnings = TRUE, recursive = FALSE, mode = "0777")
```



```{r}
# all
# table 1 (contains all years of total medical cost)

# 2023
# "https://www.e-stat.go.jp/stat-search/file-download?statInfId=000040358467&fileKind=4",

url_cost_all <- c("https://www.e-stat.go.jp/stat-search/file-download?statInfId=000040358467&fileKind=4")

```

```{r}
file_cost_all <- url_cost_all %>% str_extract("(?<=Id\\=).+(?=\\&)")

path_cost_all <- paste0("../xlsx/cost/all/", file_cost_all, ".xlsx")
```

```{r}
for (i in 1:length(url_cost_all)){
  download.file(url_cost_all[i], path_cost_all[i], mode = "wb")
  print(paste(file_cost_all[i], "downloaded"))
}
```

```{r}
# table 13 dem disease based
# has all the records

#2014
# https://www.e-stat.go.jp/stat-search/file-download?statInfId=000031457719&fileKind=0

#2015
# https://www.e-stat.go.jp/stat-search/file-download?statInfId=000031622562&fileKind=0

#2016
# https://www.e-stat.go.jp/stat-search/file-download?statInfId=000031755302&fileKind=0

#2017
# https://www.e-stat.go.jp/stat-search/file-download?statInfId=000031755302&fileKind=0

#2018
# https://www.e-stat.go.jp/stat-search/file-download?statInfId=000032028547&fileKind=0

#2019
# https://www.e-stat.go.jp/stat-search/file-download?statInfId=000032132639&fileKind=0

#2020
# https://www.e-stat.go.jp/stat-search/file-download?statInfId=000032256886&fileKind=0

#2021
# https://www.e-stat.go.jp/stat-search/file-download?statInfId=000040112149&fileKind=0

#2022
# https://www.e-stat.go.jp/stat-search/file-download?statInfId=000040214330&fileKind=4

url_cost_dem <- c("https://www.e-stat.go.jp/stat-search/file-download?statInfId=000031457719&fileKind=0",
                  "https://www.e-stat.go.jp/stat-search/file-download?statInfId=000031622562&fileKind=0",
                  "https://www.e-stat.go.jp/stat-search/file-download?statInfId=000031755302&fileKind=0",
                  "https://www.e-stat.go.jp/stat-search/file-download?statInfId=000031755302&fileKind=0",
                  "https://www.e-stat.go.jp/stat-search/file-download?statInfId=000032028547&fileKind=0",
                  "https://www.e-stat.go.jp/stat-search/file-download?statInfId=000032132639&fileKind=0",
                  "https://www.e-stat.go.jp/stat-search/file-download?statInfId=000032256886&fileKind=0",
                  "https://www.e-stat.go.jp/stat-search/file-download?statInfId=000040112149&fileKind=0",
                  "https://www.e-stat.go.jp/stat-search/file-download?statInfId=000040214330&fileKind=4"
                  )
```

```{r}
xls_xlsx <- c(rep(".xls", 4), rep(".xlsx", 5))

xls_xlsx
```


```{r}
file_cost_dem <- url_cost_dem %>% str_extract("(?<=Id\\=).+(?=\\&)")

path_cost_dem <- paste0("../xlsx/cost/dem/", file_cost_dem, xls_xlsx)
```

```{r}
for (i in 1:length(url_cost_dem)){
  download.file(url_cost_dem[i], path_cost_dem[i], mode = "wb")
  print(paste(file_cost_dem[i], "downloaded"))
}
```


```{r}

# table 15 (contains all years of total medical cost)

# 2014
# "https://www.e-stat.go.jp/stat-search/file-download?statInfId=000031457721&fileKind=0"

# 2015
# "https://www.e-stat.go.jp/stat-search/file-download?statInfId=000031622564&fileKind=0"

# 2016
# "https://www.e-stat.go.jp/stat-search/file-download?statInfId=000031755304&fileKind=0",

# 2017 xls
# "https://www.e-stat.go.jp/stat-search/file-download?statInfId=000031861566&fileKind=0"

# 2018 xlsx
# "https://www.e-stat.go.jp/stat-search/file-download?statInfId=000032028549&fileKind=0"

# 2019
# "https://www.e-stat.go.jp/stat-search/file-download?statInfId=000032132641&fileKind=0"

# 2020
# "https://www.e-stat.go.jp/stat-search/file-download?statInfId=000032256888&fileKind=0"

# 2021
# "https://www.e-stat.go.jp/stat-search/file-download?statInfId=000040112151&fileKind=0"

# 2022
# "https://www.e-stat.go.jp/stat-search/file-download?statInfId=000040214332&fileKind=4"



url_cost_sa <- c("https://www.e-stat.go.jp/stat-search/file-download?statInfId=000031457721&fileKind=0",
                "https://www.e-stat.go.jp/stat-search/file-download?statInfId=000031622564&fileKind=0",
                "https://www.e-stat.go.jp/stat-search/file-download?statInfId=000031755304&fileKind=0",
                "https://www.e-stat.go.jp/stat-search/file-download?statInfId=000031861566&fileKind=0",
                "https://www.e-stat.go.jp/stat-search/file-download?statInfId=000032028549&fileKind=0",
               "https://www.e-stat.go.jp/stat-search/file-download?statInfId=000032132641&fileKind=0",
               "https://www.e-stat.go.jp/stat-search/file-download?statInfId=000032256888&fileKind=0",
               "https://www.e-stat.go.jp/stat-search/file-download?statInfId=000040112151&fileKind=0",
                "https://www.e-stat.go.jp/stat-search/file-download?statInfId=000040214332&fileKind=4")
```

```{r}
xls_xlsx <- c(rep(".xls", 4), rep(".xlsx", 5))

xls_xlsx
```
```{r}
file_cost_sa <- url_cost_sa %>% str_extract("(?<=Id\\=).+(?=\\&)")

path_cost_sa <- paste0("../xlsx/cost/sa/", file_cost_sa, xls_xlsx)
```

```{r}
path_cost_sa
```

```{r}
for (i in 1:length(url_cost_sa)){
  download.file(url_cost_sa[i], path_cost_sa[i], mode = "wb")
  print(paste(file_cost_sa[i], "downloaded"))
}
```

# check the downloaded files


